import type { AppRecord } from "@/lib/schema";

const v = {
  status: "sourced" as const,
  lastChecked: "2026-09-07",
  note: "App policies change. Test login before you fly.",
};

export const apps: AppRecord[] = [
  {
    id: "grab",
    category: "Transportation",
    name: "Grab",
    why: "Default city transport. Prefer cars with children. Motorbike taxis are fast and a bad family idea.",
    priority: "essential",
    ios: "https://apps.apple.com/app/grab/id647268330",
    android: "https://play.google.com/store/apps/details?id=com.grabtaxi.passenger",
    offline: false,
    setupBefore: true,
    needsPhone: true,
    needsVnNumber: false,
    english: true,
    setup: "Install, add a foreign card if it works, add a backup cash plan. Turn on location. Save home as your hotel.",
    tips: "If a driver asks you to cancel and pay cash, get out. Use the in-app meter. Cars > bikes with kids.",
    verification: v,
  },
  {
    id: "gmaps",
    category: "Navigation",
    name: "Google Maps",
    why: "Walking, pins, offline area downloads. Not a Shabbat hetter for the route it draws.",
    priority: "essential",
    ios: "https://apps.apple.com/app/google-maps/id585027354",
    android: "https://play.google.com/store/apps/details?id=com.google.android.apps.maps",
    offline: true,
    setupBefore: true,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Download offline maps for Hanoi, HCMC, Hội An before you fly.",
    tips: "Walking minutes are estimates. Confirm the Chabad alley yourself.",
    verification: v,
  },
  {
    id: "translate",
    category: "Translation",
    name: "Google Translate",
    why: "Camera/Lens on menus and signs. Download Vietnamese offline.",
    priority: "essential",
    ios: "https://apps.apple.com/app/google-translate/id414706506",
    android: "https://play.google.com/store/apps/details?id=com.google.android.apps.translate",
    offline: true,
    setupBefore: true,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Download Vietnamese language pack. Enable camera translation.",
    tips: "Food phrases do not make a kitchen kosher.",
    verification: v,
  },
  {
    id: "whatsapp",
    category: "Communication",
    name: "WhatsApp",
    why: "Chabad, hotels, and drivers often live here.",
    priority: "essential",
    ios: "https://apps.apple.com/app/whatsapp-messenger/id310633997",
    android: "https://play.google.com/store/apps/details?id=com.whatsapp",
    offline: false,
    setupBefore: true,
    needsPhone: true,
    needsVnNumber: false,
    english: true,
    setup: "Register before you leave home. SMS must work on your home number.",
    tips: "Screenshot important chats before Friday.",
    verification: v,
  },
  {
    id: "zalo",
    category: "Communication",
    name: "Zalo",
    why: "Vietnamese businesses and some drivers prefer it. Useful even for foreigners.",
    priority: "useful",
    ios: "https://apps.apple.com/app/zalo/id579523206",
    android: "https://play.google.com/store/apps/details?id=com.zing.zalo",
    offline: false,
    setupBefore: true,
    needsPhone: true,
    needsVnNumber: false,
    english: true,
    setup: "OTP to your phone. English UI exists but is thinner than WhatsApp.",
    tips: "Install; don’t live in it unless a vendor requires it.",
    verification: v,
  },
  {
    id: "agoda",
    category: "Accommodation",
    name: "Agoda",
    why: "Often the relevant hotel inventory in Vietnam.",
    priority: "useful",
    offline: false,
    setupBefore: true,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Save Shabbat-neighborhood hotels. Message about keys and lights in writing.",
    tips: "A star rating is not a Shabbat rating.",
    verification: v,
  },
  {
    id: "booking",
    category: "Accommodation",
    name: "Booking.com",
    why: "Backup hotel inventory and cancellation rules.",
    priority: "useful",
    offline: false,
    setupBefore: false,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Same Shabbat questions in the message thread.",
    tips: "Compare with Agoda; don’t double-book.",
    verification: v,
  },
  {
    id: "xe",
    category: "Money",
    name: "XE",
    why: "Count zeros on đồng notes.",
    priority: "useful",
    offline: true,
    setupBefore: true,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Pin USD and VND.",
    tips: "Decline DCC at ATMs.",
    verification: v,
  },
  {
    id: "wise",
    category: "Money",
    name: "Wise",
    why: "If you already use it for travel cash. Not a Vietnam-only requirement.",
    priority: "optional",
    offline: false,
    setupBefore: true,
    needsPhone: true,
    needsVnNumber: false,
    english: true,
    setup: "Order any card before you fly if that’s your method.",
    tips: "ATMs still matter. Markets are cash.",
    verification: v,
  },
  {
    id: "vnair",
    category: "Flights",
    name: "Vietnam Airlines",
    why: "Domestic HAN–DAD–SGN. Useful if that’s the ticket you bought.",
    priority: "optional",
    offline: false,
    setupBefore: false,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Mobile boarding pass. Screenshot it.",
    tips: "Last Friday flight is not a plan.",
    verification: v,
  },
  {
    id: "vietjet",
    category: "Flights",
    name: "VietJet",
    why: "Cheap domestic. Fees for bags.",
    priority: "optional",
    offline: false,
    setupBefore: false,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Pay luggage in the app before the airport.",
    tips: "Read the bag size. Airport surprises eat Friday.",
    verification: v,
  },
  {
    id: "12go",
    category: "Trains / buses",
    name: "12Go",
    why: "One place to compare trains and vans. Confirm the operator.",
    priority: "useful",
    offline: false,
    setupBefore: false,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Screenshot tickets.",
    tips: "Sleeper trains: not Friday night arrivals.",
    verification: v,
  },
  {
    id: "airalo",
    category: "eSIM / connectivity",
    name: "Airalo (or any eSIM you already trust)",
    why: "Data for Grab on landing. Airport booths also work — pick one plan and stick to it.",
    priority: "useful",
    offline: false,
    setupBefore: true,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Install the eSIM at home on Wi-Fi. Turn it on after landing.",
    tips: "Unlock status matters. If the phone is locked, buy a physical SIM at the airport.",
    verification: v,
  },
  {
    id: "weather",
    category: "Weather",
    name: "A rain radar you already use",
    why: "Afternoon storms in the south. Typhoon window in central autumn.",
    priority: "useful",
    offline: false,
    setupBefore: false,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Save Hanoi, Hội An, HCMC.",
    tips: "Orah Today uses your weather pick, not a live feed, until you add one.",
    verification: v,
  },
  {
    id: "chabad-org",
    category: "Jewish travel",
    name: "Chabad.org locator",
    why: "Cross-check centers. Orah still wants you to confirm the Vietnam pin yourself.",
    priority: "useful",
    offline: false,
    setupBefore: false,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Save Hanoi / HCMC / Hội An pages.",
    tips: "Hanoi addresses disagree online. Call.",
    verification: v,
  },
  {
    id: "siddur",
    category: "Jewish travel",
    name: "A siddur app you already daven from",
    why: "Offline davening. Not a substitute for a paper siddur if that’s your minhag.",
    priority: "optional",
    offline: true,
    setupBefore: true,
    needsPhone: false,
    needsVnNumber: false,
    english: true,
    setup: "Download the pack on Wi-Fi.",
    tips: "Orah is not a zmanim pesak. Use your rav’s preference.",
    verification: v,
  },
];
