import type { Attraction } from "@/lib/schema";

export const attractions: Attraction[] = [
  {
    id: "hoan-kiem",
    destinationSlug: "hanoi",
    name: "Hoàn Kiếm Lake walk",
    category: "Scenic viewpoints",
    description: "Flat loop around the lake. Temples sit on the shore; you can walk the path without entering.",
    duration: "45–90 minutes",
    ages: "All ages",
    stroller: "Possible, with uneven pavement",
    walkingFromJewishArea: "Old Quarter yes; Tây Hồ no — ride before Shabbat",
    shabbatNote: "Good walking activity if you are staying nearby. No tickets.",
    religiousSite: false,
  },
  {
    id: "temple-of-literature",
    destinationSlug: "hanoi",
    name: "Temple of Literature",
    category: "Historic sites",
    description: "Confucian temple and historic university courtyards. Clearly a religious/historic worship site.",
    duration: "1.5–2 hours",
    ages: "6+",
    stroller: "Courtyards yes; thresholds and crowds",
    shabbatNote: "Ticketed. Not a Shabbat plan.",
    religiousSite: true,
  },
  {
    id: "halong-cruise",
    destinationSlug: "ha-long-bay",
    name: "Weekday bay cruise",
    category: "Boat trips",
    description: "Karst seascape. Overnight boats involve electronics, keys, and no kosher kitchen.",
    duration: "1 or 2 days",
    ages: "6+ for overnights; day boats easier with toddlers",
    stroller: "Poor",
    shabbatNote: "Never a Friday boarding for Shomer Shabbat travelers.",
    religiousSite: false,
  },
  {
    id: "trang-an",
    destinationSlug: "ninh-binh",
    name: "Tràng An / Tam Cốc boats",
    category: "Nature",
    description: "Rowed boats through limestone and paddies. Some routes pass pagodas — described so you can choose.",
    duration: "2–3 hours on the water",
    ages: "4+",
    stroller: "Leave at the dock",
    shabbatNote: "Ticketed boats. Midweek only.",
    religiousSite: false,
  },
  {
    id: "sapa-cat-cat",
    destinationSlug: "sapa",
    name: "Cat Cat village path",
    category: "Hiking",
    description: "Downhill village walk. Steep, often wet.",
    duration: "2–3 hours",
    ages: "7+ for the full descent",
    stroller: "No",
    walkingFromJewishArea: "Near town; confirm distance from Chabad",
    shabbatNote: "Ticket gate. Not for Shabbat.",
    religiousSite: false,
  },
  {
    id: "hoian-old-town",
    destinationSlug: "hoi-an",
    name: "Hội An Ancient Town",
    category: "Historic sites",
    description: "Lantern streets, river, tailor shops. Ticketed historic houses sit among free streets.",
    duration: "2–4 hours",
    ages: "All ages in daylight",
    stroller: "Crowded evenings; daytime is easier",
    walkingFromJewishArea: "About 15 minutes from published Chabad, if that pin is current",
    shabbatNote: "Streets are walkable. Skip ticketed houses and boat rides on Shabbat.",
    religiousSite: false,
  },
  {
    id: "golden-bridge",
    destinationSlug: "da-nang",
    name: "Golden Bridge, Bà Nà Hills",
    category: "Adventure",
    description: "Cable-car hill park and the gold bridge. A full paid theme-park day.",
    duration: "6–8 hours",
    ages: "5+",
    stroller: "Park paths mixed; cable car needed",
    shabbatNote: "Tickets, cable cars, and a long day. Not for Shabbat.",
    religiousSite: false,
  },
  {
    id: "hue-citadel",
    destinationSlug: "hue",
    name: "Imperial Citadel",
    category: "Historic sites",
    description: "Walled imperial city. Large, hot, ticketed.",
    duration: "2–4 hours",
    ages: "6+",
    stroller: "Some gravel and steps",
    shabbatNote: "Tickets. Midweek.",
    religiousSite: false,
  },
  {
    id: "war-remnants",
    destinationSlug: "ho-chi-minh-city",
    name: "War Remnants Museum",
    category: "Museums",
    description: "Graphic war history. Decide by age and family comfort.",
    duration: "1.5–2 hours",
    ages: "12+ for the heavier galleries",
    stroller: "Yes",
    walkingFromJewishArea: "District 3 — usually a ride, not a Shabbat walk from Đa Kao",
    shabbatNote: "Tickets and a ride. Weekday.",
    religiousSite: false,
  },
  {
    id: "saigon-walking",
    destinationSlug: "ho-chi-minh-city",
    name: "District 1 park and river edges",
    category: "Kids attractions",
    description: "Opera house lawn, walking streets, and river breeze. Churches and temples are visible; you choose whether to enter.",
    duration: "1–2 hours",
    ages: "All ages",
    stroller: "Possible on main sidewalks",
    walkingFromJewishArea: "Often walkable from a District 1 hotel",
    shabbatNote: "Best Shabbat outing if you skip paid sites and Grab.",
    religiousSite: false,
  },
  {
    id: "phu-quoc-beach",
    destinationSlug: "phu-quoc",
    name: "Resort beach day",
    category: "Beaches",
    description: "Sand and pool. Bring your own food.",
    duration: "Half day or more",
    ages: "All ages with sun care",
    stroller: "Hotel paths vary",
    shabbatNote: "Only if you are already staying on the island with food prepared.",
    religiousSite: false,
  },
];
