import type { Community } from "@/lib/schema";

export const communities: Community[] = [
  {
    id: "chabad-hcmc",
    destinationSlug: "ho-chi-minh-city",
    name: "Chabad of Vietnam — Ho Chi Minh City",
    kind: "chabad",
    address: "5A (Villa) Nguyễn Đình Chiểu, Đa Kao, District 1, Ho Chi Minh City",
    addressNote: "Published alley entrance is easy to miss. Confirm the pin before Friday.",
    phone: "84-28-39100181",
    website: "https://www.jewishvietnam.com/",
    mapsQuery: "Chabad of Vietnam 5A Nguyen Dinh Chieu District 1 Ho Chi Minh City",
    contact: "Chabad of Vietnam",
    languages: ["English", "Hebrew"],
    advanceContactRequired: true,
    services:
      "Shabbat and holiday services are offered when the center is open. Times change — write or call before you arrive.",
    meals:
      "Kosher restaurant and Shabbat meals are published on Chabad and Kosher Saigon pages. Reserve Friday dinner and Shabbat lunch in advance.",
    coords: { lat: 10.7892, lng: 106.6998 },
    verification: {
      status: "sourced",
      lastChecked: "2026-09-07",
      source: "jewishvietnam.com addresses page",
      note: "Hours and minyan can change weekly. This is not a live calendar.",
    },
  },
  {
    id: "chabad-hanoi",
    destinationSlug: "hanoi",
    name: "Chabad of Hanoi",
    kind: "chabad",
    address: "Published as 4, Ngõ 11 Tô Ngọc Vân, and also as 98 Tô Ngọc Vân, 3rd floor",
    addressNote: "Two public addresses appear online. Confirm the current location before you walk on Shabbat.",
    phone: "84-83-872-8225",
    website: "https://www.jewishhanoi.com/",
    mapsQuery: "Chabad of Hanoi To Ngoc Van",
    contact: "Chabad of Hanoi (public listings name Rabbi Levi & Mushky Laine)",
    languages: ["English", "Hebrew"],
    advanceContactRequired: true,
    services: "Tourist info pages describe prayer and Shabbat meals. Confirm this week’s schedule directly.",
    meals: "Chabad publishes kosher food, hotel delivery, and catering. Order before Friday.",
    coords: { lat: 21.0568, lng: 105.8275 },
    verification: {
      status: "needs-confirm",
      lastChecked: "2026-09-07",
      source: "jewishhanoi.com and lubavitch.com center listing",
      note: "Address listings disagree. Contact the house before travel.",
    },
  },
  {
    id: "chabad-hoi-an",
    destinationSlug: "hoi-an",
    name: "Chabad Hoi An",
    kind: "chabad",
    address: "570A Cửa Đại, Cẩm Châu, Hội An, Quảng Nam",
    addressNote: "Published as ~1.5 km / 15 minutes from the river and night market.",
    phone: "+84901356770",
    website: "https://www.jewishvietnam.com/templates/articlecco_cdo/aid/5715178/jewish/Chabad-Hoi-An.htm",
    mapsQuery: "570A Cua Dai Cam Chau Hoi An",
    contact: "Public page names Rabbi Menachem and Rochali Fridman",
    languages: ["English", "Hebrew"],
    advanceContactRequired: true,
    services: "Friday evening at sundown and Shabbat morning, followed by meals — confirm before arrival.",
    meals: "Shabbat meals by advance notice. Weekday restaurant hours are published on the Chabad Hoi An page.",
    coords: { lat: 15.8875, lng: 108.3512 },
    verification: {
      status: "sourced",
      lastChecked: "2026-09-07",
      source: "jewishvietnam.com Chabad Hoi An page",
    },
  },
  {
    id: "chabad-sapa",
    destinationSlug: "sapa",
    name: "Chabad of Sapa",
    kind: "chabad",
    address: "12A Thác Bạc, Sa Pa, Lào Cai (as published on travel and business listings)",
    addressNote: "Newer listing. Confirm it is open the week you travel.",
    mapsQuery: "Chabad of Sapa 12A Thac Bac Sapa",
    languages: ["English", "Hebrew"],
    advanceContactRequired: true,
    services: "Travel listings mention Shabbat meals and a shul. No official weekly schedule was confirmed here.",
    meals: "Do not assume weekday or Shabbat meals without a direct confirmation.",
    coords: { lat: 22.336, lng: 103.8445 },
    verification: {
      status: "unverified",
      lastChecked: "2026-09-07",
      source: "Third-party travel listings and a Vietnamese business registration for 12A Thác Bạc",
      note: "Contact Chabad of Vietnam or the Sapa house before treating this as a Shabbat plan.",
    },
  },
];
