import type { CountryRecord, Destination } from "@/lib/schema";

export const countries: CountryRecord[] = [
  {
    slug: "vietnam",
    name: "Vietnam",
    localName: "Việt Nam",
    status: "live",
    summary: "The first live country guide. Plan around Friday in Hanoi, Hội An, and Saigon.",
    image: "/destinations/halong.jpg",
    shabbatCities: ["hanoi", "hoi-an", "ho-chi-minh-city", "sapa"],
  },
  {
    slug: "thailand",
    name: "Thailand",
    localName: "ประเทศไทย",
    status: "preview",
    summary: "Same data model as Vietnam. Bangkok is the usual Shabbat city — listings coming next.",
    image: "/destinations/hoian.jpg",
    shabbatCities: ["bangkok"],
  },
  {
    slug: "japan",
    name: "Japan",
    localName: "日本",
    status: "preview",
    summary: "Tokyo and Kyoto will use the same Shabbat-first itinerary engine.",
    image: "/destinations/hanoi.jpg",
    shabbatCities: ["tokyo"],
  },
  {
    slug: "italy",
    name: "Italy",
    localName: "Italia",
    status: "preview",
    summary: "Rome and Milan are sketched so the worldwide URL scheme is real, not theoretical.",
    image: "/destinations/saigon.jpg",
    shabbatCities: ["rome"],
  },
];

const noEruv = {
  exists: false as const,
  notes: "Do not assume an eruv. Confirm with the local community.",
  verification: {
    status: "unverified" as const,
    lastChecked: "2026-09-07",
    note: "Preview country — eruv research is not complete.",
  },
};

export const previewDestinations: Destination[] = [
  {
    slug: "bangkok",
    countrySlug: "thailand",
    name: "Bangkok",
    region: "central",
    summary: "Preview city. The schema is live so Thailand can fill in without a redesign.",
    whyVisit: "Usual Shabbat base for kosher travelers in Thailand.",
    howLong: "Treat as a Friday city once listings are verified.",
    image: "/destinations/hoian.jpg",
    coords: { lat: 13.7563, lng: 100.5018 },
    tzid: "Asia/Bangkok",
    airports: ["BKK", "DMK"],
    transferMinutesFromAirport: 50,
    jewishInfrastructure: "strong",
    shabbatBase: {
      recommended: true,
      neighborhood: "Confirm the current Chabad / kosher cluster before booking.",
      walkingNotes: "Walk the route in daylight. This page is a scaffold, not a verified pin.",
      fridayAdvice: "Do not treat this preview as a live meal calendar.",
    },
    eruv: noEruv,
    weather: { bestMonths: "Nov–Feb", rainy: "May–Oct", dry: "Nov–Apr", notes: "Hot year-round." },
    gettingThere: "BKK or DMK.",
    gettingAround: "BTS, MRT, Grab.",
    familyNotes: "Mall air-con helps. Confirm kosher meals before you land.",
    nearby: [],
  },
  {
    slug: "tokyo",
    countrySlug: "japan",
    name: "Tokyo",
    region: "north",
    summary: "Preview city for the worldwide Orah schema.",
    whyVisit: "Japan’s main Jewish-infrastructure city.",
    howLong: "Scaffold only.",
    image: "/destinations/hanoi.jpg",
    coords: { lat: 35.6762, lng: 139.6503 },
    tzid: "Asia/Tokyo",
    airports: ["HND", "NRT"],
    transferMinutesFromAirport: 60,
    jewishInfrastructure: "strong",
    shabbatBase: {
      recommended: true,
      neighborhood: "To be verified.",
      walkingNotes: "Not yet mapped.",
      fridayAdvice: "Preview — do not book from this page alone.",
    },
    eruv: noEruv,
    weather: { bestMonths: "Mar–May, Oct–Nov", rainy: "Jun–Jul", dry: "Dec–Feb", notes: "Four seasons." },
    gettingThere: "HND or NRT.",
    gettingAround: "Trains.",
    familyNotes: "Pack kosher snacks. Convenience stores are not kosher.",
    nearby: [],
  },
  {
    slug: "rome",
    countrySlug: "italy",
    name: "Rome",
    region: "central",
    summary: "Preview city proving /italy/rome works on the same engine as /vietnam/hanoi.",
    whyVisit: "Historic Jewish quarter plus a large kosher scene — to be catalogued.",
    howLong: "Scaffold only.",
    image: "/destinations/saigon.jpg",
    coords: { lat: 41.9028, lng: 12.4964 },
    tzid: "Europe/Rome",
    airports: ["FCO"],
    transferMinutesFromAirport: 50,
    jewishInfrastructure: "strong",
    shabbatBase: {
      recommended: true,
      neighborhood: "Ghetto / via other verified addresses — not listed yet.",
      walkingNotes: "Eruv and walking map are not verified here.",
      fridayAdvice: "Preview country.",
    },
    eruv: {
      exists: false,
      notes: "Rome may have an eruv in some periods. This preview does not assert one.",
      verification: {
        status: "unverified",
        lastChecked: "2026-09-07",
        note: "Never assume an eruv from this scaffold.",
      },
    },
    weather: { bestMonths: "Apr–Jun, Sep–Oct", rainy: "Nov–Mar", dry: "Jun–Aug", notes: "Hot summers." },
    gettingThere: "FCO.",
    gettingAround: "Walk, tram, taxi.",
    familyNotes: "Cobblestones are hard on strollers.",
    nearby: [],
  },
];
