import type { Destination } from "@/lib/schema";

const tzid = "Asia/Ho_Chi_Minh";
const noEruv = {
  exists: false as const,
  notes: "No eruv is published for this city. Do not assume one exists.",
  verification: {
    status: "sourced" as const,
    lastChecked: "2026-09-07",
    source: "No public eruv listing found for Vietnam cities",
    note: "Treat as no eruv unless a local rav tells you otherwise.",
  },
};

export const destinations: Destination[] = [
  {
    slug: "hanoi",
    countrySlug: "vietnam",
    name: "Hanoi",
    localName: "Hà Nội",
    region: "north",
    summary: "Vietnam’s capital and the strongest northern base for kosher meals, minyan, and Shabbat.",
    whyVisit:
      "Old Quarter streets, lakes, museums, and easy day trips to Ninh Bình or Hạ Long — if you return before Friday afternoon.",
    howLong: "3–4 nights as a Shabbat base; 2 nights if you are only passing through.",
    image: "/destinations/hanoi.jpg",
    coords: { lat: 21.0285, lng: 105.8542 },
    tzid,
    airports: ["HAN"],
    transferMinutesFromAirport: 60,
    jewishInfrastructure: "strong",
    shabbatBase: {
      recommended: true,
      neighborhood: "Tây Hồ / Tô Ngọc Vân area near Chabad, or a hotel you can walk from after confirming the current address.",
      walkingNotes: "Hanoi traffic is intense. Confirm the current Chabad pin and walk it in daylight on Friday.",
      fridayAdvice: "Land at HAN by early afternoon. Immigration plus a 45–90 minute transfer can erase a late arrival.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Oct–Apr for cooler, drier days",
      rainy: "May–Sep",
      dry: "Oct–Apr",
      notes: "Hot and humid most of the year. Pack layers for winter damp (Dec–Feb).",
    },
    gettingThere: "Nội Bài (HAN) is the main northern gateway. Airport taxis and Grab are the usual city transfer.",
    gettingAround: "Grab cars are simpler with children than motorbike taxis. Old Quarter is walkable; longer hops need a car.",
    familyNotes: "Hoàn Kiếm Lake loop is stroller-possible. Sidewalks are uneven. Carry a baby carrier for markets.",
    nearby: ["ninh-binh", "ha-long-bay", "sapa"],
  },
  {
    slug: "ha-long-bay",
    countrySlug: "vietnam",
    name: "Hạ Long Bay",
    localName: "Vịnh Hạ Long",
    region: "north",
    summary: "Limestone karsts and overnight boats — treat this as a weekday trip, not a Shabbat base.",
    whyVisit: "The classic northern seascape. Best as a one- or two-night weekday cruise out of Hanoi.",
    howLong: "1–2 nights midweek. Be back in Hanoi Friday afternoon if you need Chabad.",
    image: "/destinations/halong.jpg",
    coords: { lat: 20.9101, lng: 107.1839 },
    tzid,
    airports: ["HAN"],
    transferMinutesFromAirport: 180,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "Stay in Hanoi for Shabbat. Overnight boats are a poor fit for Shomer Shabbat travel.",
      walkingNotes: "No known synagogue or kosher kitchen on the water.",
      fridayAdvice: "Do not book a Friday boarding. Transfer from Hanoi is 3–4 hours with traffic.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Oct–Apr",
      rainy: "May–Sep",
      dry: "Oct–Apr",
      notes: "Fog and drizzle are common in winter. Summers are hot with storm risk.",
    },
    gettingThere: "Private car or tour van from Hanoi (3–4 hours). Some travelers use Hạ Long’s own cruise harbor.",
    gettingAround: "Boats and tenders. Not a walking city.",
    familyNotes: "Life jackets, rails, and motion sickness matter more than strollers. Overnight cruises are tiring with toddlers.",
    nearby: ["hanoi", "ninh-binh"],
  },
  {
    slug: "ninh-binh",
    countrySlug: "vietnam",
    name: "Ninh Bình",
    localName: "Ninh Bình",
    region: "north",
    summary: "Rice paddies and river valleys — an easy weekday nature stop from Hanoi.",
    whyVisit: "Tam Cốc / Tràng An boat rides and limestone countryside without the Hạ Long crowds.",
    howLong: "1–2 nights midweek. Return to Hanoi before Friday if you need kosher Shabbat.",
    image: "/destinations/hanoi.jpg",
    coords: { lat: 20.2506, lng: 105.9744 },
    tzid,
    airports: ["HAN"],
    transferMinutesFromAirport: 140,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "No known Jewish infrastructure. Use Hanoi as the Shabbat city.",
      walkingNotes: "Rural roads, not a synagogue walking radius.",
      fridayAdvice: "Leave for Hanoi by early Friday. The drive is about two hours in good traffic.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Oct–Apr",
      rainy: "May–Sep",
      dry: "Oct–Apr",
      notes: "Flooded paddies are photogenic after rain; boats may cancel in storms.",
    },
    gettingThere: "Car or limousine van from Hanoi (about 2 hours). Trains stop at Ninh Bình station.",
    gettingAround: "Private driver, bicycle, or boat tours. Grab coverage is thinner than in Hanoi.",
    familyNotes: "Boats are gentle. Bring sun cover and snacks. Bathrooms on routes can be basic.",
    nearby: ["hanoi", "ha-long-bay"],
  },
  {
    slug: "sapa",
    countrySlug: "vietnam",
    name: "Sapa",
    localName: "Sa Pa",
    region: "north",
    summary: "Mountain town with a reported Chabad house — confirm hours before you treat it as a Shabbat base.",
    whyVisit: "Terraced hills, cooler air, and trekking. A possible northern Shabbat if Chabad is open that week.",
    howLong: "2–3 nights. Add a buffer night if you are arriving on a sleeper train.",
    image: "/destinations/hanoi.jpg",
    coords: { lat: 22.3364, lng: 103.8438 },
    tzid,
    airports: ["HAN"],
    transferMinutesFromAirport: 330,
    jewishInfrastructure: "seasonal",
    shabbatBase: {
      recommended: true,
      neighborhood: "Town center near Thác Bạc if the published Chabad address is current.",
      walkingNotes: "Steep streets. Confirm the pin and walk it before Shabbat.",
      fridayAdvice: "Do not rely on a Friday night train arrival. Come Thursday or early Friday.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Sep–Nov and Mar–May",
      rainy: "May–Sep",
      dry: "Oct–Apr, but winter is cold and foggy",
      notes: "Pack real layers. Sapa is much cooler than Hanoi.",
    },
    gettingThere: "Sleeper train or 5–6 hour car from Hanoi. Weather can slow the mountain road.",
    gettingAround: "Walking in town; private drivers for valley treks.",
    familyNotes: "Stairs and wet paths. Carriers beat strollers. Rice-terrace walks can be slippery.",
    nearby: ["hanoi", "ha-giang"],
  },
  {
    slug: "ha-giang",
    countrySlug: "vietnam",
    name: "Hà Giang",
    localName: "Hà Giang",
    region: "north",
    summary: "Loop-country mountains with no known Jewish infrastructure. Weekday only for observant travelers.",
    whyVisit: "The far-north loop is spectacular. Plan it Monday–Thursday and be in Hanoi or Sapa for Shabbat.",
    howLong: "3–4 midweek days for the loop. Never as a Friday destination if you need minyan or kosher meals.",
    image: "/destinations/hanoi.jpg",
    coords: { lat: 22.8026, lng: 104.9784 },
    tzid,
    airports: ["HAN"],
    transferMinutesFromAirport: 420,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "Do not plan Shabbat here if you need Chabad, minyan, or kosher meals.",
      walkingNotes: "Remote roads. No known synagogue.",
      fridayAdvice: "Be back in Hanoi (or confirmed-open Sapa) by Friday afternoon. The drive is long.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Oct–Apr",
      rainy: "May–Sep",
      dry: "Oct–Apr",
      notes: "Fog and landslides can close roads in the wet season.",
    },
    gettingThere: "Car from Hanoi (7+ hours) or via Sapa. Not a last-minute Friday hop.",
    gettingAround: "Private driver or motorbike loop. Motorbikes are a poor fit with children.",
    familyNotes: "Long mountain days. Motion sickness is common. Skip if you need a predictable kosher kitchen.",
    nearby: ["sapa", "hanoi"],
  },
  {
    slug: "da-nang",
    countrySlug: "vietnam",
    name: "Da Nang",
    localName: "Đà Nẵng",
    region: "central",
    summary: "Beach city and airport hub. For Shabbat, most observant travelers continue 45 minutes to Hội An.",
    whyVisit: "Beaches, Marble Mountains, and the easiest central airport. Hội An is the Jewish-infrastructure town.",
    howLong: "1 night as a transit city, or beach days if you will spend Shabbat in Hội An.",
    image: "/destinations/hoian.jpg",
    coords: { lat: 16.0544, lng: 108.2022 },
    tzid,
    airports: ["DAD"],
    transferMinutesFromAirport: 25,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "Use Hội An for Shabbat. Da Nang has no published Chabad house.",
      walkingNotes: "Beach hotels are not a synagogue walking radius.",
      fridayAdvice: "Land at DAD and transfer to Hội An with a large Friday buffer.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Feb–May",
      rainy: "Sep–Dec (typhoon window)",
      dry: "Feb–Aug",
      notes: "Central Vietnam’s autumn rains can be intense.",
    },
    gettingThere: "Đà Nẵng International (DAD). Direct domestic flights from HAN and SGN.",
    gettingAround: "Grab is reliable. Taxi to Hội An is 45–60 minutes.",
    familyNotes: "Beach hotels are easy with kids. Cross the road with extreme care.",
    nearby: ["hoi-an", "hue"],
  },
  {
    slug: "hoi-an",
    countrySlug: "vietnam",
    name: "Hội An",
    localName: "Hội An",
    region: "central",
    summary: "Lantern town with a Chabad house and kosher restaurant — the central Shabbat base.",
    whyVisit: "Walkable old town, tailors, river evenings, and published kosher meals at Chabad.",
    howLong: "3 nights including Shabbat, or 2 nights midweek.",
    image: "/destinations/hoian.jpg",
    coords: { lat: 15.8801, lng: 108.338 },
    tzid,
    airports: ["DAD"],
    transferMinutesFromAirport: 50,
    jewishInfrastructure: "strong",
    shabbatBase: {
      recommended: true,
      neighborhood: "Cẩm Châu / Cửa Đại Road near the published Chabad address, or Old Town if you confirm the walk.",
      walkingNotes: "Chabad publishes about 1.5 km / 15 minutes from the river and night market. Walk it Friday.",
      fridayAdvice: "Land DAD by early afternoon. Reserve Shabbat meals in advance.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Feb–May",
      rainy: "Sep–Dec",
      dry: "Feb–Aug",
      notes: "Flooding can close Old Town streets in autumn.",
    },
    gettingThere: "Fly into Da Nang (DAD), then 45–60 minutes by car.",
    gettingAround: "Walking and bicycles in Old Town. Grab for the beach and Chabad if you are staying farther out.",
    familyNotes: "Old Town is atmospheric but crowded at night. Daytime is easier with strollers.",
    nearby: ["da-nang", "hue"],
  },
  {
    slug: "hue",
    countrySlug: "vietnam",
    name: "Huế",
    localName: "Huế",
    region: "central",
    summary: "Imperial city — weekday culture stop. Spend Shabbat in Hội An.",
    whyVisit: "Citadel, tombs, and a slower central-Vietnam pace.",
    howLong: "1–2 nights midweek.",
    image: "/destinations/hoian.jpg",
    coords: { lat: 16.4637, lng: 107.5909 },
    tzid,
    airports: ["DAD", "HUI"],
    transferMinutesFromAirport: 20,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "No known Chabad. Continue to Hội An for Friday.",
      walkingNotes: "The citadel is large; it is not a Jewish walking map.",
      fridayAdvice: "The road to Hội An is 2.5–3.5 hours. Leave Thursday or very early Friday.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Feb–May",
      rainy: "Sep–Dec",
      dry: "Feb–Aug",
      notes: "Huế is one of the wetter central cities in autumn.",
    },
    gettingThere: "Train or car from Da Nang / Hội An. Some flights use Phu Bai (HUI).",
    gettingAround: "Private driver for tombs. Citadel can be walked or cycled.",
    familyNotes: "Lots of walking and sun. Bring water and a carrier for palace grounds.",
    nearby: ["da-nang", "hoi-an"],
  },
  {
    slug: "nha-trang",
    countrySlug: "vietnam",
    name: "Nha Trang",
    localName: "Nha Trang",
    region: "south",
    summary: "Beach city with no known Jewish infrastructure. Weekday resort stop only.",
    whyVisit: "Swimming and island trips if you can self-cater kosher food.",
    howLong: "2 midweek nights. Do not land here on Friday if you need Chabad.",
    image: "/destinations/saigon.jpg",
    coords: { lat: 12.2388, lng: 109.1967 },
    tzid,
    airports: ["CXR"],
    transferMinutesFromAirport: 40,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "No published Chabad. Use Ho Chi Minh City or Hội An for Shabbat.",
      walkingNotes: "Beach strip hotels, not a synagogue radius.",
      fridayAdvice: "If you must stay, arrive Thursday with packed food. Better: fly to SGN or DAD Thursday.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Jan–Aug",
      rainy: "Sep–Dec",
      dry: "Jan–Aug",
      notes: "Hot year-round. Sea can be rough in the wet months.",
    },
    gettingThere: "Cam Ranh (CXR) is 30–45 minutes from town.",
    gettingAround: "Grab along the beach. Boats for islands.",
    familyNotes: "Hotel pools help. Watch motorbike traffic on the promenade.",
    nearby: ["da-lat", "ho-chi-minh-city"],
  },
  {
    slug: "da-lat",
    countrySlug: "vietnam",
    name: "Da Lat",
    localName: "Đà Lạt",
    region: "south",
    summary: "Cool highland town. No known Chabad — a weekday nature break.",
    whyVisit: "Pine hills, cooler nights, and a change from the coast.",
    howLong: "2 midweek nights.",
    image: "/destinations/saigon.jpg",
    coords: { lat: 11.9404, lng: 108.4583 },
    tzid,
    airports: ["DLI"],
    transferMinutesFromAirport: 35,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "No published Jewish community. Return to Ho Chi Minh City for Shabbat.",
      walkingNotes: "Hills and mist, not a synagogue map.",
      fridayAdvice: "The road or flight back to SGN needs a Thursday or early-Friday plan.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Dec–Mar",
      rainy: "May–Oct",
      dry: "Nov–Apr",
      notes: "Mornings can be cold by Vietnam standards. Pack a fleece.",
    },
    gettingThere: "Flights to Liên Khương (DLI) or a 6–7 hour car from HCMC / Nha Trang.",
    gettingAround: "Private car. Distances between viewpoints add up.",
    familyNotes: "Cooler sleep is a gift with children. Many attractions are outdoor and hilly.",
    nearby: ["nha-trang", "ho-chi-minh-city"],
  },
  {
    slug: "ho-chi-minh-city",
    countrySlug: "vietnam",
    name: "Ho Chi Minh City",
    localName: "Thành phố Hồ Chí Minh",
    region: "south",
    summary: "Saigon is the southern Shabbat city: Chabad, kosher restaurant, and the easiest airport.",
    whyVisit: "Food energy, museums, day trips to the Mekong — and a published kosher kitchen at Chabad.",
    howLong: "3–4 nights including Shabbat.",
    image: "/destinations/saigon.jpg",
    coords: { lat: 10.8231, lng: 106.6297 },
    tzid,
    airports: ["SGN"],
    transferMinutesFromAirport: 45,
    jewishInfrastructure: "strong",
    shabbatBase: {
      recommended: true,
      neighborhood: "District 1 / Đa Kao near 5A Nguyễn Đình Chiểu. Confirm the alley entrance before Friday.",
      walkingNotes: "Chabad sits in a villa alley. Walk the route in daylight. Traffic is relentless.",
      fridayAdvice: "Land SGN by early afternoon. Pre-order meals. District 1 hotels shorten the walk.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Dec–Apr",
      rainy: "May–Nov (short downpours)",
      dry: "Dec–Apr",
      notes: "Hot year-round. Rain is usually a sharp afternoon storm, not an all-day washout.",
    },
    gettingThere: "Tân Sơn Nhất (SGN). Immigration and baggage can be slow at peak hours.",
    gettingAround: "Grab cars. District 1 is partly walkable; crossings are stressful with children.",
    familyNotes: "Hotel pools matter. Notre Dame / opera park pockets are useful. Carry a carrier in markets.",
    nearby: ["mekong-delta", "phu-quoc"],
  },
  {
    slug: "mekong-delta",
    countrySlug: "vietnam",
    name: "Mekong Delta",
    localName: "Đồng bằng sông Cửu Long",
    region: "south",
    summary: "River markets and orchards — a weekday day trip or overnight from Saigon.",
    whyVisit: "Boats, floating markets, and village lunches. Bring your own food if you keep kosher.",
    howLong: "Day trip or 1 midweek night in Cần Thơ.",
    image: "/destinations/saigon.jpg",
    coords: { lat: 10.0452, lng: 105.7469 },
    tzid,
    airports: ["SGN"],
    transferMinutesFromAirport: 210,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "Return to District 1, Ho Chi Minh City, for Shabbat.",
      walkingNotes: "River towns, not a synagogue radius.",
      fridayAdvice: "A Mekong day trip on Friday is a poor idea. Traffic back to SGN can stall.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Dec–Apr",
      rainy: "May–Nov",
      dry: "Dec–Apr",
      notes: "Very hot. Boats have little shade on some routes.",
    },
    gettingThere: "Private car from HCMC (2–4 hours depending on which town).",
    gettingAround: "Boats and a driver. Not a Grab-first region.",
    familyNotes: "Life jackets and sun hats. Toilets can be basic. Skip long boat days with infants.",
    nearby: ["ho-chi-minh-city"],
  },
  {
    slug: "phu-quoc",
    countrySlug: "vietnam",
    name: "Phú Quốc",
    localName: "Phú Quốc",
    region: "south",
    summary: "Island beaches with no known Chabad. Pack food or treat it as a weekday resort.",
    whyVisit: "Sand and hotel pools after a Saigon Shabbat.",
    howLong: "3 midweek nights. Fly back to SGN Thursday if you need Friday in the city.",
    image: "/destinations/saigon.jpg",
    coords: { lat: 10.2899, lng: 103.984 },
    tzid,
    airports: ["PQC"],
    transferMinutesFromAirport: 30,
    jewishInfrastructure: "none-known",
    shabbatBase: {
      recommended: false,
      neighborhood: "No published Jewish community. Self-cater or return to Ho Chi Minh City.",
      walkingNotes: "Resort distances are long. Not a synagogue map.",
      fridayAdvice: "Island time plus a flight is a fragile Friday plan. Arrive Thursday or stay put with packed food.",
    },
    eruv: noEruv,
    weather: {
      bestMonths: "Nov–Apr",
      rainy: "May–Oct",
      dry: "Nov–Apr",
      notes: "Wet season can close beach days. Ferries are more weather-sensitive than flights.",
    },
    gettingThere: "Flights from SGN and HAN to PQC. Some ferries from the mainland.",
    gettingAround: "Hotel shuttles, Grab in busier areas, or a private driver.",
    familyNotes: "Resort kids’ clubs vary. Bring baby food; island groceries are limited for kosher products.",
    nearby: ["ho-chi-minh-city"],
  },
];

export const country = {
  slug: "vietnam",
  name: "Vietnam",
  localName: "Việt Nam",
  summary:
    "A full travel guide with a deeper layer for kosher and Shomer Shabbat travelers. Plan the route around Friday, not the other way around.",
  shabbatCities: ["hanoi", "hoi-an", "ho-chi-minh-city", "sapa"],
};
