import type { Neighborhood } from "@/lib/schema";

export const neighborhoods: Neighborhood[] = [
  {
    id: "hanoi-tay-ho",
    destinationSlug: "hanoi",
    name: "Tây Hồ",
    localName: "Tây Hồ",
    whyStay: "Sleep and a realistic Shabbat walk once you confirm the current Chabad pin on Tô Ngọc Vân.",
    atmosphere: "Lake, expats, quieter nights than the Old Quarter.",
    familyFit: "Best default with children. Apartments and a fridge are easier here.",
    jewishRelevance: "This is the published Chabad cluster — confirm the address; listings disagree.",
    transport: "Grab to the Old Quarter is 25–40 minutes. Not a stroll.",
    nightlife: "Restaurants, not a party grid.",
    shabbatWalk: "West Lake path if the pin is here. Walk it Friday in daylight.",
  },
  {
    id: "hanoi-old-quarter",
    destinationSlug: "hanoi",
    name: "Old Quarter",
    localName: "Phố cổ",
    whyStay: "Weekday atmosphere. Weak default for Shomer Shabbat unless you will not walk to Tây Hồ.",
    atmosphere: "Tight, loud, 36 streets.",
    familyFit: "Hard with strollers. Fun for one weekday night.",
    jewishRelevance: "Usually too far to walk to Tây Hồ Chabad. Ride before candles.",
    transport: "Walk internally. Grab out.",
    nightlife: "Busy until late. Weekend night market.",
    shabbatWalk: "Hoàn Kiếm loop if you sleep here — not Chabad.",
  },
  {
    id: "hanoi-hoan-kiem",
    destinationSlug: "hanoi",
    name: "Hoàn Kiếm / French Quarter edge",
    localName: "Hoàn Kiếm",
    whyStay: "Lake access, slightly wider streets than the 36-street core.",
    atmosphere: "Tourist-central, walkable lake.",
    familyFit: "Better sidewalks than Hang Dao. Still noisy.",
    jewishRelevance: "Not the Chabad neighborhood.",
    transport: "Walk the lake. Grab to Tây Hồ.",
    nightlife: "Evening lake traffic.",
    shabbatWalk: "The lake loop.",
  },
  {
    id: "hanoi-ba-dinh",
    destinationSlug: "hanoi",
    name: "Ba Đình",
    whyStay: "Museums, Lotte, quieter diplomatic streets.",
    atmosphere: "Official, leafy in spots.",
    familyFit: "Fine for weekdays. Not a Jewish walking map.",
    jewishRelevance: "Ride to Chabad.",
    transport: "Grab. Some walks between museums.",
    nightlife: "Low.",
  },
  {
    id: "hcmc-d1",
    destinationSlug: "ho-chi-minh-city",
    name: "District 1",
    localName: "Quận 1",
    whyStay: "Parks, walking street, hotels. Measure the alley to Chabad anyway.",
    atmosphere: "Saigon energy, loud, convenient.",
    familyFit: "Hotel pools matter. Sidewalks are a fight.",
    jewishRelevance: "Best chance of a walking-radius hotel to 5A Nguyễn Đình Chiểu.",
    transport: "Walk pockets. Grab for everything else.",
    nightlife: "Walking street evenings.",
    shabbatWalk: "Opera lawn and river edge if you already sleep here.",
  },
  {
    id: "hcmc-dakao",
    destinationSlug: "ho-chi-minh-city",
    name: "Đa Kao",
    whyStay: "Closest published cluster to Chabad’s villa alley.",
    atmosphere: "Residential-central mix. Easy to miss the alley.",
    familyFit: "Look for a fridge. Less ‘pretty’ than Đồng Khởi.",
    jewishRelevance: "This is the Shabbat neighborhood if the pin stays put.",
    transport: "Walk once you know the alley. Do it Friday.",
    nightlife: "Local rather than showpiece.",
    shabbatWalk: "Only after you walk the actual gate.",
  },
  {
    id: "hcmc-d3",
    destinationSlug: "ho-chi-minh-city",
    name: "District 3",
    whyStay: "War Remnants, slightly calmer streets.",
    atmosphere: "Cafés, tree streets.",
    familyFit: "Fine weekdays.",
    jewishRelevance: "Usually a ride to Chabad — not the Friday default.",
    transport: "Grab.",
    nightlife: "Low.",
  },
  {
    id: "hcmc-d7",
    destinationSlug: "ho-chi-minh-city",
    name: "District 7 / Phú Mỹ Hưng",
    whyStay: "Stroller pavement and malls. Wrong neighborhood if you need a Shabbat walk to Chabad.",
    atmosphere: "Planned, wide, less ‘Saigon.’",
    familyFit: "Excellent for toddlers on weekdays.",
    jewishRelevance: "Too far to walk to Đa Kao.",
    transport: "Grab 20–35 minutes to D1.",
    nightlife: "Mall.",
  },
  {
    id: "hoian-old-town",
    destinationSlug: "hoi-an",
    name: "Ancient Town",
    localName: "Phố cổ",
    whyStay: "Lanterns at the door. Longer walk to published Chabad on Cửa Đại.",
    atmosphere: "Crowded nights, magic, tailors.",
    familyFit: "Daytime better than 8pm.",
    jewishRelevance: "Test the walk to 570A Cửa Đại before you commit to Friday here.",
    transport: "Walk and bikes. Grab to the beach.",
    nightlife: "Lantern peak.",
    shabbatWalk: "Free streets only — skip ticket houses.",
  },
  {
    id: "hoian-cua-dai",
    destinationSlug: "hoi-an",
    name: "Cửa Đại / Cẩm Châu",
    whyStay: "Closest published area to Chabad. Larger hotels, some apartments.",
    atmosphere: "Road + beach hotels, less lantern.",
    familyFit: "Easier sleep. Beach nearby.",
    jewishRelevance: "Default Shomer Shabbat neighborhood if the pin is current.",
    transport: "Grab or bike to Old Town 10–15 minutes.",
    nightlife: "Low.",
    shabbatWalk: "Measure minutes to 570A Cửa Đại.",
  },
  {
    id: "hoian-an-bang",
    destinationSlug: "hoi-an",
    name: "An Bàng",
    whyStay: "Beach village. Pretty. Not the Chabad walk.",
    atmosphere: "Sand, loungers, sun.",
    familyFit: "Great with kids midweek.",
    jewishRelevance: "Ride before Friday if you need Chabad.",
    transport: "Grab 15–20 minutes to Old Town.",
    nightlife: "Beach bars.",
  },
  {
    id: "danang-my-khe",
    destinationSlug: "da-nang",
    name: "Mỹ Khê beach strip",
    whyStay: "Beach hotels, airport 25 minutes. Sleep here midweek; move to Hội An for Shabbat.",
    atmosphere: "Resort road, sea.",
    familyFit: "Easy. Crossing the road is the danger.",
    jewishRelevance: "No published Chabad. Hội An is the Friday city.",
    transport: "Grab along the strip. 45–60 minutes to Hội An.",
    nightlife: "Dragon Bridge on some evenings.",
  },
];
