import type { Phrase } from "@/lib/schema";

const food = "This does not make the kitchen kosher.";

export const phrases: Phrase[] = [
  { id: "hello", category: "basics", en: "Hello", vi: "Xin chào", say: "sin chow", saveable: true },
  { id: "thanks", category: "basics", en: "Thank you", vi: "Cảm ơn", say: "kahm un", saveable: true },
  { id: "please", category: "basics", en: "Please", vi: "Làm ơn", say: "lahm un", saveable: true },
  { id: "yes", category: "basics", en: "Yes", vi: "Vâng / Dạ", say: "vung / za", saveable: true },
  { id: "no", category: "basics", en: "No", vi: "Không", say: "khom", saveable: true },
  { id: "sorry", category: "basics", en: "Sorry", vi: "Xin lỗi", say: "sin loy", saveable: true },
  { id: "excuse", category: "basics", en: "Excuse me", vi: "Xin lỗi, cho hỏi", say: "sin loy cho hoy", saveable: true },
  { id: "where", category: "directions", en: "Where is…?", vi: "… ở đâu?", say: "uh doh", saveable: true },
  { id: "left", category: "directions", en: "Left", vi: "Bên trái", say: "ben chai", saveable: true },
  { id: "right", category: "directions", en: "Right", vi: "Bên phải", say: "ben fai", saveable: true },
  { id: "straight", category: "directions", en: "Straight", vi: "Đi thẳng", say: "dee thang", saveable: true },
  { id: "near", category: "directions", en: "Near", vi: "Gần", say: "gun", saveable: true },
  { id: "far", category: "directions", en: "Far", vi: "Xa", say: "sa", saveable: true },
  { id: "stop-here", category: "grab", en: "Stop here", vi: "Dừng lại đây", say: "zung lai day", showToDriver: true, saveable: true },
  { id: "take-me", category: "grab", en: "Please take me here", vi: "Làm ơn đưa tôi đến địa chỉ này", say: "lahm un dua toy den dee-a chee nai", showToDriver: true, saveable: true },
  { id: "meter", category: "grab", en: "Please use the meter / app", vi: "Làm ơn chạy theo app", say: "lahm un chay theo app", showToDriver: true, saveable: true },
  { id: "how-long", category: "grab", en: "How long?", vi: "Bao lâu nữa?", say: "bow lau nua", saveable: true },
  { id: "how-much-ride", category: "grab", en: "How much?", vi: "Bao nhiêu tiền?", say: "bow nyew tee-en", saveable: true },
  { id: "wrong", category: "grab", en: "Wrong location", vi: "Sai địa chỉ", say: "sai dee-a chee", showToDriver: true, saveable: true },
  { id: "reservation", category: "hotel", en: "I have a reservation", vi: "Tôi có đặt phòng", say: "toy kaw dat fom", showToDriver: true, saveable: true },
  { id: "checkin", category: "hotel", en: "Can I check in?", vi: "Tôi nhận phòng được chưa?", say: "toy nyun fom duoc chua", saveable: true },
  { id: "luggage", category: "hotel", en: "Can I leave my luggage?", vi: "Tôi gửi hành lý được không?", say: "toy gui hang lee duoc khom", saveable: true },
  { id: "other-room", category: "hotel", en: "Do you have another room?", vi: "Còn phòng khác không?", say: "con fom kac khom", saveable: true },
  { id: "ac-broken", category: "hotel", en: "The air conditioning isn’t working", vi: "Máy lạnh không hoạt động", say: "may lanh khom hwot dung", saveable: true },
  { id: "towel", category: "hotel", en: "Can I have another towel?", vi: "Cho thêm khăn tắm", say: "cho tem khun tam", saveable: true },
  { id: "physical-key", category: "hotel", en: "Can I get a physical room key?", vi: "Cho tôi chìa khóa phòng (không phải thẻ từ)", say: "cho toy chee-a khwa fom", saveable: true },
  { id: "how-much", category: "shopping", en: "How much?", vi: "Bao nhiêu tiền?", say: "bow nyew tee-en", saveable: true },
  { id: "expensive", category: "shopping", en: "Too expensive", vi: "Đắt quá", say: "dat wa", saveable: true },
  { id: "cheaper", category: "shopping", en: "Can you make it cheaper?", vi: "Bớt được không?", say: "bot duoc khom", saveable: true },
  { id: "size", category: "shopping", en: "Do you have another size?", vi: "Còn size khác không?", say: "con size kac khom", saveable: true },
  { id: "cash", category: "shopping", en: "Cash", vi: "Tiền mặt", say: "tee-en mat", saveable: true },
  { id: "card", category: "shopping", en: "Card", vi: "Thẻ", say: "teh", saveable: true },
  { id: "no-pork", category: "food", en: "No pork", vi: "Không thịt heo", say: "khom tit hay-o", caution: food, saveable: true },
  { id: "no-shell", category: "food", en: "No shellfish", vi: "Không hải sản", say: "khom hi san", caution: food, saveable: true },
  { id: "veg", category: "food", en: "Vegetarian", vi: "Đồ chay", say: "daw chai", caution: "Vegetarian is not kosher. Broth, fish sauce, and shared woks are common.", saveable: true },
  { id: "no-fishsauce", category: "food", en: "No fish sauce", vi: "Không nước mắm", say: "khom nuoc mam", caution: food, saveable: true },
  { id: "no-meat", category: "food", en: "No meat", vi: "Không thịt", say: "khom tit", caution: food, saveable: true },
  { id: "allergy", category: "food", en: "I have an allergy", vi: "Tôi bị dị ứng", say: "toy bee zee ung", saveable: true },
  { id: "peanut", category: "food", en: "Peanuts", vi: "Đậu phộng / lạc", say: "dow fong / lac", saveable: true },
  { id: "hospital", category: "medical", en: "Hospital", vi: "Bệnh viện", say: "ben vee-en", showToDriver: true, saveable: true },
  { id: "doctor", category: "medical", en: "Doctor", vi: "Bác sĩ", say: "bac see", saveable: true },
  { id: "pharmacy", category: "medical", en: "Pharmacy", vi: "Nhà thuốc", say: "nya twok", showToDriver: true, saveable: true },
  { id: "help-med", category: "medical", en: "I need help", vi: "Tôi cần giúp đỡ", say: "toy cun zoop der", saveable: true },
  { id: "child-sick", category: "medical", en: "My child is sick", vi: "Con tôi bị ốm", say: "con toy bee om", saveable: true },
  { id: "ambulance", category: "medical", en: "Call an ambulance", vi: "Gọi cấp cứu", say: "goy kup cuu", saveable: true },
  { id: "baby", category: "family", en: "Baby", vi: "Em bé", say: "em beh", saveable: true },
  { id: "child", category: "family", en: "Child", vi: "Trẻ em", say: "che em", saveable: true },
  { id: "diapers", category: "family", en: "Diapers", vi: "Tã / bỉm", say: "ta / bim", saveable: true },
  { id: "bathroom", category: "family", en: "Bathroom", vi: "Nhà vệ sinh", say: "nya veh sin", saveable: true },
  { id: "stroller", category: "family", en: "Stroller", vi: "Xe đẩy", say: "seh day", saveable: true },
  { id: "carseat", category: "family", en: "Car seat", vi: "Ghế an toàn cho bé", say: "geh an toan cho beh", saveable: true },
  { id: "police", category: "emergency", en: "Police", vi: "Công an", say: "com an", saveable: true },
  { id: "help", category: "emergency", en: "Help", vi: "Cứu tôi với", say: "cuu toy vuh", saveable: true },
  { id: "lost", category: "emergency", en: "I am lost", vi: "Tôi bị lạc", say: "toy bee lac", saveable: true },
  { id: "phone-stolen", category: "emergency", en: "My phone was stolen", vi: "Điện thoại tôi bị mất trộm", say: "dee-en twai toy bee mat trom", saveable: true },
  { id: "passport-stolen", category: "emergency", en: "My passport was stolen", vi: "Hộ chiếu tôi bị mất trộm", say: "haw chee-ow toy bee mat trom", saveable: true },
  { id: "emergency", category: "emergency", en: "Emergency", vi: "Khẩn cấp", say: "khun kup", saveable: true },
  { id: "n1", category: "numbers", en: "1", vi: "Một", say: "mote", saveable: true },
  { id: "n2", category: "numbers", en: "2", vi: "Hai", say: "hai", saveable: true },
  { id: "n3", category: "numbers", en: "3", vi: "Ba", say: "ba", saveable: true },
  { id: "n4", category: "numbers", en: "4", vi: "Bốn", say: "bone", saveable: true },
  { id: "n5", category: "numbers", en: "5", vi: "Năm", say: "nam", saveable: true },
  { id: "n6", category: "numbers", en: "6", vi: "Sáu", say: "sow", saveable: true },
  { id: "n7", category: "numbers", en: "7", vi: "Bảy", say: "bai", saveable: true },
  { id: "n8", category: "numbers", en: "8", vi: "Tám", say: "tam", saveable: true },
  { id: "n9", category: "numbers", en: "9", vi: "Chín", say: "chin", saveable: true },
  { id: "n10", category: "numbers", en: "10", vi: "Mười", say: "muh-uh", saveable: true },
  { id: "n20", category: "numbers", en: "20", vi: "Hai mươi", say: "hai muh-uh", saveable: true },
  { id: "n50", category: "numbers", en: "50", vi: "Năm mươi", say: "nam muh-uh", saveable: true },
  { id: "n100", category: "numbers", en: "100", vi: "Một trăm", say: "mote cham", saveable: true },
  { id: "n1000", category: "numbers", en: "1,000", vi: "Một nghìn", say: "mote ngeen", saveable: true },
  { id: "airport", category: "travel", en: "Airport", vi: "Sân bay", say: "sun bai", showToDriver: true, saveable: true },
  { id: "train-st", category: "travel", en: "Train station", vi: "Ga tàu", say: "ga tau", showToDriver: true, saveable: true },
  { id: "bus-st", category: "travel", en: "Bus station", vi: "Bến xe", say: "ben seh", showToDriver: true, saveable: true },
  { id: "hotel-w", category: "travel", en: "Hotel", vi: "Khách sạn", say: "khak san", showToDriver: true, saveable: true },
  { id: "restaurant", category: "travel", en: "Restaurant", vi: "Nhà hàng", say: "nya hang", saveable: true },
  { id: "entrance", category: "travel", en: "Entrance", vi: "Lối vào", say: "loy vow", saveable: true },
  { id: "exit", category: "travel", en: "Exit", vi: "Lối ra", say: "loy za", saveable: true },
  { id: "ticket", category: "travel", en: "Ticket", vi: "Vé", say: "veh", saveable: true },
];
