import type { TransportOption, TransportRoute } from "@/lib/schema";

const v = {
  status: "live-external" as const,
  lastChecked: "2026-09-07",
  note: "Times and dong bands change. Confirm in the booking app the week you travel.",
};

function opt(row: TransportOption): TransportOption {
  return row;
}

function pair(
  id: string,
  fromSlug: string,
  toSlug: string,
  options: TransportOption[],
  recommendation: TransportRoute["recommendation"],
): TransportRoute {
  return { id, fromSlug, toSlug, options, recommendation, verification: v };
}

export const routes: TransportRoute[] = [
  pair(
    "hanoi-ninh-binh",
    "hanoi",
    "ninh-binh",
    [
      opt({
        mode: "van",
        name: "Limousine van",
        durationMin: 110,
        durationMax: 150,
        cost: "About 150,000–250,000₫ per seat",
        comfort: "OK with kids if you book a whole row",
        kids: "Better than the train with a stroller",
        luggage: "Under the van",
        overnight: false,
        motion: "Highway, usually fine",
        book: "The day before",
        pickup: "Old Quarter / hotel",
        dropoff: "Tam Cốc or Hoa Lư",
        fridayNote: "Fine midweek. Leave Hanoi early. Be back for Thursday night if Friday is Hanoi.",
      }),
      opt({
        mode: "train",
        name: "SE train to Ninh Bình station",
        durationMin: 110,
        durationMax: 140,
        cost: "Seat fare, then a taxi to the docks",
        comfort: "AC seats",
        kids: "Bathroom on board",
        luggage: "Overhead",
        overnight: false,
        motion: "Low",
        book: "App or station",
        pickup: "Hanoi station",
        dropoff: "Ninh Bình station — not the boat",
        fridayNote: "Weekday. Still need a taxi to Tam Cốc.",
      }),
      opt({
        mode: "driver",
        name: "Private car",
        durationMin: 110,
        durationMax: 150,
        cost: "Day-hire band, not a meter",
        comfort: "Best with children and packed food",
        kids: "Car seat if you brought one",
        luggage: "Trunk",
        overnight: false,
        motion: "Low",
        book: "WhatsApp driver in writing",
        pickup: "Hotel",
        dropoff: "Dock then Hanoi dinner",
        fridayNote: "The right Friday-adjacent choice: go and return midweek.",
      }),
    ],
    {
      family: "Private car or a whole van row",
      backpacker: "Limousine van",
      overnight: "Only if you want Hang Múa sunrise",
      friday: "Do not day-trip Friday. Traffic plus boats will eat candles.",
    },
  ),
  pair(
    "hanoi-ha-long-bay",
    "hanoi",
    "ha-long-bay",
    [
      opt({
        mode: "van",
        name: "Tour van to the harbor",
        durationMin: 180,
        durationMax: 270,
        cost: "Usually bundled with the boat",
        comfort: "Long",
        kids: "Hard with toddlers",
        luggage: "Van",
        overnight: false,
        motion: "Highway then boat",
        book: "With the boat, not a street tout",
        pickup: "Hotel 7–8am",
        dropoff: "Harbor, then back to Hanoi same night on a day boat",
        fridayNote: "Never a Friday boarding.",
      }),
      opt({
        mode: "driver",
        name: "Private car",
        durationMin: 180,
        durationMax: 240,
        cost: "Day hire",
        comfort: "Stops when kids need them",
        kids: "Best of the bad options",
        luggage: "Trunk",
        overnight: false,
        motion: "Long",
        book: "In writing",
        pickup: "Hotel",
        dropoff: "Harbor",
        fridayNote: "Thursday is the last sensible day boat.",
      }),
    ],
    {
      family: "Private car + day boat, or skip if under 5",
      backpacker: "Bundled van + day boat",
      overnight: "Cruise Sun–Wed only",
      friday: "Do not board Friday. Be in Hanoi afternoon.",
    },
  ),
  pair(
    "hanoi-sapa",
    "hanoi",
    "sapa",
    [
      opt({
        mode: "van",
        name: "Limousine van",
        durationMin: 300,
        durationMax: 390,
        cost: "About 300,000–450,000₫",
        comfort: "Windy mountain end",
        kids: "Motion sickness common",
        luggage: "Van",
        overnight: false,
        motion: "High on the last hour",
        book: "Day before",
        pickup: "Hotel",
        dropoff: "Sapa town",
        fridayNote: "Arrive Thursday. Do not rely on Friday afternoon vans.",
      }),
      opt({
        mode: "train",
        name: "Sleeper train + morning transfer",
        durationMin: 420,
        durationMax: 540,
        cost: "Soft sleeper band + shuttle",
        comfort: "Overnight, shared cabin",
        kids: "OK if they sleep. Bathroom is a squat plus motion",
        luggage: "Cabin",
        overnight: true,
        motion: "Medium",
        book: "Train app in advance",
        pickup: "Hanoi station evening",
        dropoff: "Lào Cai then 1 hour to Sapa",
        fridayNote: "Do not take a Friday night train if you need candles in a city.",
      }),
      opt({
        mode: "driver",
        name: "Private car",
        durationMin: 300,
        durationMax: 390,
        cost: "Day hire, highest",
        comfort: "Stops",
        kids: "Best",
        luggage: "Trunk",
        overnight: false,
        motion: "Still a mountain road",
        book: "In writing",
        pickup: "Hotel",
        dropoff: "Hotel Sapa",
        fridayNote: "Thursday drive.",
      }),
    ],
    {
      family: "Limousine van or private car, Thursday",
      backpacker: "Sleeper train",
      overnight: "Train",
      friday: "No Friday night arrival. Confirm Chabad before you treat Sapa as Shabbat.",
    },
  ),
  pair(
    "hanoi-ha-giang",
    "hanoi",
    "ha-giang",
    [
      opt({
        mode: "driver",
        name: "Private driver for the loop",
        durationMin: 420,
        durationMax: 540,
        cost: "Multi-day hire",
        comfort: "The only family-sane way",
        kids: "Still a poor toddler trip",
        luggage: "Trunk",
        overnight: false,
        motion: "Very high",
        book: "Loop package in writing",
        pickup: "Hanoi hotel",
        dropoff: "Loop start",
        fridayNote: "Finish Thursday. Friday on the loop is a block if you need kosher meals.",
      }),
      opt({
        mode: "sleeper-bus",
        name: "Sleeper bus",
        durationMin: 420,
        durationMax: 540,
        cost: "Cheap",
        comfort: "Poor",
        kids: "No",
        luggage: "Hold",
        overnight: true,
        motion: "High",
        book: "Night before",
        pickup: "Mỹ Đình area",
        dropoff: "Hà Giang town",
        fridayNote: "Not a Friday plan.",
      }),
    ],
    {
      family: "Usually skip. If not, private driver, midweek only",
      backpacker: "Sleeper bus + motorbike loop — not with kids",
      overnight: "Bus",
      friday: "Hà Giang on a Friday will not work for Shomer + kosher.",
    },
  ),
  pair(
    "hanoi-da-nang",
    "hanoi",
    "da-nang",
    [
      opt({
        mode: "flight",
        name: "HAN–DAD",
        durationMin: 80,
        durationMax: 100,
        cost: "Varies wildly — check the week of",
        comfort: "Airport time dominates",
        kids: "Standard domestic",
        luggage: "Airline rules",
        overnight: false,
        motion: "Low",
        book: "Airline app",
        pickup: "Nội Bài",
        dropoff: "DAD then 45–60 min to Hội An",
        fridayNote: "Last Friday flight is not a plan. Land Thursday.",
      }),
    ],
    {
      family: "Morning flight Thursday if Friday is Hội An",
      backpacker: "Same flight",
      overnight: "No night train worth it vs the flight",
      friday: "Do not take the last Friday HAN–DAD.",
    },
  ),
  pair(
    "hanoi-ho-chi-minh-city",
    "hanoi",
    "ho-chi-minh-city",
    [
      opt({
        mode: "flight",
        name: "HAN–SGN",
        durationMin: 120,
        durationMax: 140,
        cost: "Shop VN / VietJet / Bamboo",
        comfort: "Standard",
        kids: "Fine",
        luggage: "Watch VietJet fees",
        overnight: false,
        motion: "Low",
        book: "Airline app",
        pickup: "HAN",
        dropoff: "SGN + 45 min to D1",
        fridayNote: "Early Thursday/Friday morning only if you must. Prefer Thursday.",
      }),
    ],
    {
      family: "Flight. Train is 30+ hours — skip with kids",
      backpacker: "Flight unless you want the train as an experience",
      overnight: "Reunification express is a choice, not a shortcut",
      friday: "Do not land SGN at 16:00 Friday and expect Chabad meals.",
    },
  ),
  pair(
    "da-nang-hoi-an",
    "da-nang",
    "hoi-an",
    [
      opt({
        mode: "grab",
        name: "Grab car",
        durationMin: 40,
        durationMax: 70,
        cost: "Typically 250,000–400,000₫ — confirm in app",
        comfort: "The default",
        kids: "Car, not a bike",
        luggage: "Fits a family if you don’t overpack",
        overnight: false,
        motion: "Low",
        book: "Open Grab after bags",
        pickup: "DAD or Mỹ Khê",
        dropoff: "Cửa Đại or Old Town",
        fridayNote: "Leave DAD with a large Friday buffer. This is 45–60 minutes, not ‘next door.’",
      }),
      opt({
        mode: "van",
        name: "Airport shuttle van",
        durationMin: 45,
        durationMax: 80,
        cost: "Per seat, cheaper, slower",
        comfort: "Stops",
        kids: "Worse than Grab car",
        luggage: "Tight",
        overnight: false,
        motion: "Low",
        book: "Hotel or desk",
        pickup: "DAD",
        dropoff: "Hotel list",
        fridayNote: "Shuttles wait for full vans. Friday is the wrong day to wait.",
      }),
    ],
    {
      family: "Grab car",
      backpacker: "Shuttle or Grab",
      overnight: "n/a",
      friday: "Land early. Pre-order Hội An meals.",
    },
  ),
  pair(
    "hoi-an-hue",
    "hoi-an",
    "hue",
    [
      opt({
        mode: "driver",
        name: "Private car",
        durationMin: 150,
        durationMax: 210,
        cost: "Day hire / one-way band",
        comfort: "Best",
        kids: "Yes",
        luggage: "Trunk",
        overnight: false,
        motion: "Medium (Hải Vân pass if via Da Nang)",
        book: "In writing",
        pickup: "Hội An hotel",
        dropoff: "Huế hotel",
        fridayNote: "2.5–3.5 hours. Leave Thursday or very early Friday only if you must — better Thursday.",
      }),
      opt({
        mode: "train",
        name: "Da Nang–Huế train + two Grabs",
        durationMin: 180,
        durationMax: 270,
        cost: "Train cheap, transfers not",
        comfort: "Scenic pass",
        kids: "More logistics",
        luggage: "Train",
        overnight: false,
        motion: "Low on rails",
        book: "Train + Grab",
        pickup: "Grab to DAD station area / Da Nang station",
        dropoff: "Huế station",
        fridayNote: "Too many links for Friday.",
      }),
    ],
    {
      family: "Private car Thursday",
      backpacker: "Bus or train",
      overnight: "n/a",
      friday: "The road to Hội An is 2.5–3.5 hours. Leave Thursday.",
    },
  ),
  pair(
    "hue-phong-nha",
    "hue",
    "phong-nha",
    [
      opt({
        mode: "driver",
        name: "Private car",
        durationMin: 180,
        durationMax: 270,
        cost: "One-way or 2-day hire",
        comfort: "The realistic option",
        kids: "Long but direct",
        luggage: "Trunk",
        overnight: false,
        motion: "Medium",
        book: "With the cave hotel",
        pickup: "Huế",
        dropoff: "Phong Nha town",
        fridayNote: "Caves are not a Friday product. Leave Thursday for Hội An after the caves.",
      }),
    ],
    {
      family: "Private car, two nights, then south",
      backpacker: "Bus if it actually stops in Phong Nha",
      overnight: "Required — not a Huế afternoon",
      friday: "Be in Hội An, not a cave mouth.",
    },
  ),
  pair(
    "ho-chi-minh-city-mekong-delta",
    "ho-chi-minh-city",
    "mekong-delta",
    [
      opt({
        mode: "driver",
        name: "Day-tour car to Mỹ Tho",
        durationMin: 90,
        durationMax: 150,
        cost: "Bundled tour or private",
        comfort: "Highway",
        kids: "OK with packed lunch",
        luggage: "Day bag",
        overnight: false,
        motion: "Low then boat",
        book: "Day before",
        pickup: "D1 hotel early",
        dropoff: "Back to D1 before dark",
        fridayNote: "A Mekong Friday is a poor idea.",
      }),
      opt({
        mode: "driver",
        name: "Private to Cần Thơ",
        durationMin: 180,
        durationMax: 270,
        cost: "Higher",
        comfort: "Long",
        kids: "Overnight only",
        luggage: "Trunk",
        overnight: true,
        motion: "Medium",
        book: "In writing",
        pickup: "HCMC",
        dropoff: "Cần Thơ",
        fridayNote: "Return to D1 Thursday.",
      }),
    ],
    {
      family: "Mỹ Tho day trip",
      backpacker: "Bus to Cần Thơ",
      overnight: "Cần Thơ for Cai Rang dawn",
      friday: "Do not go. Traffic back to SGN stalls.",
    },
  ),
  pair(
    "ho-chi-minh-city-phu-quoc",
    "ho-chi-minh-city",
    "phu-quoc",
    [
      opt({
        mode: "flight",
        name: "SGN–PQC",
        durationMin: 50,
        durationMax: 70,
        cost: "Shop the week of",
        comfort: "Easy",
        kids: "Fine",
        luggage: "Airline",
        overnight: false,
        motion: "Low",
        book: "Airline app",
        pickup: "SGN",
        dropoff: "PQC + 20–50 min to the hotel side you picked",
        fridayNote: "Island + flight is a fragile Friday. Arrive Thursday or stay put with packed food.",
      }),
    ],
    {
      family: "Flight after Saigon Shabbat, back Thursday",
      backpacker: "Same",
      overnight: "n/a",
      friday: "Do not connect a late SGN flight to PQC on Friday.",
    },
  ),
  pair(
    "ho-chi-minh-city-da-lat",
    "ho-chi-minh-city",
    "da-lat",
    [
      opt({
        mode: "flight",
        name: "SGN–DLI",
        durationMin: 50,
        durationMax: 70,
        cost: "Often cheap",
        comfort: "Then 30–40 min road",
        kids: "Fine",
        luggage: "Airline",
        overnight: false,
        motion: "Low then hills",
        book: "Airline",
        pickup: "SGN",
        dropoff: "Liên Khương",
        fridayNote: "Be back Thursday if Friday is Saigon.",
      }),
      opt({
        mode: "driver",
        name: "Road 6–8 hours",
        durationMin: 360,
        durationMax: 480,
        cost: "Tiring",
        comfort: "Windy",
        kids: "Poor",
        luggage: "Trunk",
        overnight: false,
        motion: "High",
        book: "Only if you like cars",
        pickup: "HCMC",
        dropoff: "Da Lat",
        fridayNote: "No.",
      }),
    ],
    {
      family: "Flight",
      backpacker: "Sleeper bus",
      overnight: "Bus",
      friday: "Road or flight back Thursday.",
    },
  ),
  pair(
    "ho-chi-minh-city-nha-trang",
    "ho-chi-minh-city",
    "nha-trang",
    [
      opt({
        mode: "flight",
        name: "SGN–CXR",
        durationMin: 60,
        durationMax: 80,
        cost: "Shop",
        comfort: "Then 30–45 min to town",
        kids: "Fine",
        luggage: "Airline",
        overnight: false,
        motion: "Low",
        book: "Airline",
        pickup: "SGN",
        dropoff: "Cam Ranh",
        fridayNote: "Do not land Friday if you need Chabad — there isn’t one.",
      }),
    ],
    {
      family: "Flight midweek",
      backpacker: "Train is long; flight wins",
      overnight: "Train if you want it",
      friday: "Nha Trang is not a Friday city.",
    },
  ),
  pair(
    "sapa-ha-giang",
    "sapa",
    "ha-giang",
    [
      opt({
        mode: "driver",
        name: "Mountain transfer",
        durationMin: 240,
        durationMax: 360,
        cost: "Private",
        comfort: "Hard",
        kids: "No",
        luggage: "Trunk",
        overnight: false,
        motion: "Very high",
        book: "Loop operator",
        pickup: "Sapa",
        dropoff: "Hà Giang / loop",
        fridayNote: "Only midweek, and only if Hanoi Shabbat is already in the plan after.",
      }),
    ],
    {
      family: "Skip",
      backpacker: "Driver or motorbike — your risk",
      overnight: "n/a",
      friday: "Do not connect these on Thursday afternoon hoping for Friday anywhere Jewish.",
    },
  ),
];
