import type { Destination } from "@/lib/schema";

type Extra = Pick<
  Destination,
  | "bestFor"
  | "whoWillLove"
  | "whoMightNot"
  | "feelsLike"
  | "dailyBudget"
  | "minNights"
  | "maxNights"
  | "neighborhoodIds"
  | "dayTripIds"
  | "continueTrip"
  | "familyByAge"
  | "jewishSummary"
>;

const budget = (low: string, typical: string, note: string) => ({ low, typical, note });

export const travelProfiles: Record<string, Extra> = {
  hanoi: {
    bestFor: ["culture", "kids", "day trips", "northern Shabbat base"],
    whoWillLove: "Families who want a kosher kitchen and a real city, then one nature day.",
    whoMightNot: "People who want beaches first, or a Friday in the mountains.",
    feelsLike: "Dense, loud, lake pockets, and a Shabbat that only works if you pick the right neighborhood.",
    dailyBudget: budget("400,000–800,000₫ non-food", "Hotel + Grab dominate", "Kosher meals are a Chabad bill, not street food."),
    minNights: 3,
    maxNights: 5,
    neighborhoodIds: ["hanoi-tay-ho", "hanoi-old-quarter", "hanoi-hoan-kiem", "hanoi-ba-dinh"],
    dayTripIds: ["ninh-binh-day-from-hanoi", "halong-day-from-hanoi"],
    continueTrip: ["hanoi-ninh-binh", "hanoi-ha-long-bay", "hanoi-sapa", "hanoi-da-nang", "hanoi-ho-chi-minh-city"],
    familyByAge: {
      "0-2": "Carrier, Tây Hồ apartment, skip overnight cruises.",
      "3-5": "Lake loop, ethnology outdoor houses, water puppets. Not train street.",
      "6-9": "Ninh Bình boats work. Hạ Long is a long day.",
      "10-12": "Citadel museums and a nature day.",
      teens: "Old Quarter at night once, then a real hike or cruise weekday.",
    },
    jewishSummary: "Strongest northern base — confirm the Chabad address; two pins exist online.",
  },
  "ho-chi-minh-city": {
    bestFor: ["city energy", "kosher kitchen", "Mekong day", "southern Shabbat"],
    whoWillLove: "Anyone landing SGN who needs meals and a minyan.",
    whoMightNot: "Beach-first travelers who refuse a city Shabbat.",
    feelsLike: "Heat, Grab, one walkable Jewish alley if you measure it.",
    dailyBudget: budget("400,000–900,000₫", "D1 hotels cost more than they look", "Chabad meals by reservation."),
    minNights: 3,
    maxNights: 5,
    neighborhoodIds: ["hcmc-d1", "hcmc-dakao", "hcmc-d3", "hcmc-d7"],
    dayTripIds: ["mekong-day-from-saigon", "cu-chi"],
    continueTrip: ["ho-chi-minh-city-mekong-delta", "ho-chi-minh-city-phu-quoc", "ho-chi-minh-city-da-lat", "ho-chi-minh-city-nha-trang"],
    familyByAge: {
      "0-2": "Hotel pool, D1 park, skip Củ Chi.",
      "3-5": "Zoo/gardens, walking street evening, not War Remnants upstairs.",
      "6-9": "Independence Palace + park. Mekong day with packed lunch.",
      "10-12": "War Remnants possible. Talk first.",
      teens: "War Remnants, palace, rooftop skip.",
    },
    jewishSummary: "Published Chabad villa in Đa Kao — walk the alley in daylight.",
  },
  "hoi-an": {
    bestFor: ["walkable town", "family", "central Shabbat", "tailors"],
    whoWillLove: "Almost every first-timer who can land DAD Thursday.",
    whoMightNot: "People who hate crowds or need a synagogue in Da Nang itself.",
    feelsLike: "Lanterns + a beach road. Jewish life sits on Cửa Đại, not in the ticket houses.",
    dailyBudget: budget("500,000–1,000,000₫", "Old Town hotels spike", "Reserve Shabbat meals."),
    minNights: 3,
    maxNights: 5,
    neighborhoodIds: ["hoian-old-town", "hoian-cua-dai", "hoian-an-bang"],
    dayTripIds: ["ba-na-from-hoian", "marble-mountains"],
    continueTrip: ["da-nang-hoi-an", "hoi-an-hue"],
    familyByAge: {
      "0-2": "Daytime Old Town, An Bàng, skip lantern crush.",
      "3-5": "Beach + short street walks. Basket boat if they sit still.",
      "6-9": "Bà Nà as a full day. Not stacked with Marble Mountains.",
      "10-12": "Tailors with a parent. Night lanterns once.",
      teens: "Bà Nà, lanterns, beach road.",
    },
    jewishSummary: "Central Shabbat city. 570A Cửa Đại — confirm meals in advance.",
  },
  "da-nang": {
    bestFor: ["beach", "airport", "Bà Nà"],
    whoWillLove: "Families who want sand midweek.",
    whoMightNot: "Anyone who needs Friday minyan in this city — go to Hội An.",
    feelsLike: "A beach airport with a theme-park mountain.",
    dailyBudget: budget("400,000–900,000₫", "Beach hotels", "Eat packed or in Hội An."),
    minNights: 1,
    maxNights: 3,
    neighborhoodIds: ["danang-my-khe"],
    dayTripIds: ["golden-bridge"],
    continueTrip: ["da-nang-hoi-an", "hanoi-da-nang", "hoi-an-hue"],
    familyByAge: {
      "0-2": "Beach hotel. Careful crossings.",
      "3-5": "Mỹ Khê + Dragon Bridge evening.",
      "6-9": "Bà Nà full day.",
      "10-12": "Marble Mountains or Sơn Trà, not both with Bà Nà.",
      teens: "Sơn Trà viewpoints.",
    },
    jewishSummary: "No published Chabad. Transfer to Hội An for Friday.",
  },
  "ninh-binh": {
    bestFor: ["nature", "boats", "weekday from Hanoi"],
    whoWillLove: "Anyone who wants karst without the cruise.",
    whoMightNot: "Friday travelers who still need kosher Shabbat.",
    feelsLike: "A nature day with a dock, not a Jewish town.",
    dailyBudget: budget("Boat tickets + driver", "Day trip cheaper than overnight", "Bring all food."),
    minNights: 0,
    maxNights: 1,
    neighborhoodIds: [],
    dayTripIds: ["trang-an", "tam-coc"],
    continueTrip: ["hanoi-ninh-binh"],
    familyByAge: {
      "0-2": "Possible on a boat with sun cover; bathrooms are basic.",
      "3-5": "Tràng An is the gentler boat.",
      "6-9": "One boat, skip the tomb stack.",
      "10-12": "Hang Múa if they like stairs.",
      teens: "Hang Múa sunrise.",
    },
    jewishSummary: "None known. Sleep Hanoi for Shabbat.",
  },
  "ha-long-bay": {
    bestFor: ["boats", "weekday wow"],
    whoWillLove: "People who accept a long transfer.",
    whoMightNot: "Toddlers, Friday boarders, anyone needing a kitchen.",
    feelsLike: "The postcard — treat it as a weekday product.",
    dailyBudget: budget("Day boat cheaper than overnight", "Overnight is the splurge", "No kosher kitchen."),
    minNights: 0,
    maxNights: 2,
    neighborhoodIds: [],
    dayTripIds: ["halong-cruise", "lan-ha"],
    continueTrip: ["hanoi-ha-long-bay"],
    familyByAge: {
      "0-2": "Usually skip overnight. Day boat is still long.",
      "3-5": "Day boat only, life jackets.",
      "6-9": "Day boat. Kayak add-on if they swim.",
      "10-12": "Overnight only Sun–Wed.",
      teens: "Lan Ha if they want quieter water.",
    },
    jewishSummary: "None on the water. Hanoi is Friday.",
  },
  hue: {
    bestFor: ["history", "weekday culture"],
    whoWillLove: "People who like ruins in the heat.",
    whoMightNot: "Families already tired from Bà Nà.",
    feelsLike: "Imperial and wet in autumn.",
    dailyBudget: budget("Citadel ticket + driver", "One tomb extra", "Packed food."),
    minNights: 1,
    maxNights: 2,
    neighborhoodIds: [],
    dayTripIds: ["phong-nha-from-hue"],
    continueTrip: ["hoi-an-hue", "hue-phong-nha"],
    familyByAge: {
      "0-2": "Hard. Heat and gravel.",
      "3-5": "Short citadel, then shade.",
      "6-9": "Citadel morning.",
      "10-12": "Citadel + Khải Định.",
      teens: "Tomb circuit if they want it.",
    },
    jewishSummary: "None known. Hội An for Friday.",
  },
  sapa: {
    bestFor: ["mountains", "cool air", "seasonal Shabbat if open"],
    whoWillLove: "Trekkers who confirm Chabad that week.",
    whoMightNot: "Anyone arriving on a Friday train.",
    feelsLike: "Steep, fog, stairs.",
    dailyBudget: budget("Cable car is the big ticket", "Town hotels", "Confirm meals."),
    minNights: 2,
    maxNights: 3,
    neighborhoodIds: [],
    dayTripIds: ["fansipan"],
    continueTrip: ["hanoi-sapa", "sapa-ha-giang"],
    familyByAge: {
      "0-2": "Carriers only. Skip wet descents.",
      "3-5": "Town square + cable car.",
      "6-9": "Cat Cat if dry.",
      "10-12": "Cat Cat + Fansipan.",
      teens: "Tả Van if fit.",
    },
    jewishSummary: "Reported house on Thác Bạc — unverified. Confirm before you treat it as a base.",
  },
  "ha-giang": {
    bestFor: ["mountains", "weekday loop"],
    whoWillLove: "Adults with a driver and no Friday constraint in the far north.",
    whoMightNot: "Toddlers, kosher-dependent families, Friday arrivals.",
    feelsLike: "The loop, not a town.",
    dailyBudget: budget("Private driver is the cost", "Homestays", "Pack all food."),
    minNights: 3,
    maxNights: 4,
    neighborhoodIds: [],
    dayTripIds: [],
    continueTrip: ["hanoi-ha-giang", "sapa-ha-giang"],
    familyByAge: {
      "0-2": "Usually a poor choice — long driving, no kitchen.",
      "3-5": "Same. Skip.",
      "6-9": "Only if they handle 7-hour cars.",
      "10-12": "Maybe, with a driver, midweek.",
      teens: "The actual audience.",
    },
    jewishSummary: "None known. Friday here is a block if you need Chabad.",
  },
  "nha-trang": {
    bestFor: ["beach", "weekday resort"],
    whoWillLove: "Swimmers with packed food.",
    whoMightNot: "Friday arrivals who need Chabad.",
    feelsLike: "A beach city without a Jewish map.",
    dailyBudget: budget("Hotel + beach", "VinWonders is a splurge day", "Pack food."),
    minNights: 2,
    maxNights: 3,
    neighborhoodIds: [],
    dayTripIds: ["vinwonders"],
    continueTrip: ["ho-chi-minh-city-nha-trang"],
    familyByAge: {
      "0-2": "Hotel pool beats municipal beach.",
      "3-5": "Pool + short beach.",
      "6-9": "VinWonders if you want a park day.",
      "10-12": "Island boat maybe.",
      teens: "Island boat.",
    },
    jewishSummary: "None known.",
  },
  "da-lat": {
    bestFor: ["cool weather", "kids parks"],
    whoWillLove: "Anyone melting in Saigon.",
    whoMightNot: "Friday needs in HCMC — leave Thursday.",
    feelsLike: "Hills, mist, ticket parks.",
    dailyBudget: budget("Many small tickets", "Don’t buy every viewpoint", "Packed food."),
    minNights: 2,
    maxNights: 3,
    neighborhoodIds: [],
    dayTripIds: [],
    continueTrip: ["ho-chi-minh-city-da-lat"],
    familyByAge: {
      "0-2": "Lake loop, skip Crazy House stairs.",
      "3-5": "Lake + Valley of Love maybe.",
      "6-9": "Crazy House with a hand on the rail.",
      "10-12": "Đatanla coaster.",
      teens: "Coaster + one viewpoint.",
    },
    jewishSummary: "None known.",
  },
  "mekong-delta": {
    bestFor: ["boats", "weekday from Saigon"],
    whoWillLove: "People who want river life once.",
    whoMightNot: "Friday drivers.",
    feelsLike: "Heat, boats, tourist loops that still show water life.",
    dailyBudget: budget("Day tour vs Cần Thơ night", "Bring lunch", "Toilets basic."),
    minNights: 0,
    maxNights: 1,
    neighborhoodIds: [],
    dayTripIds: ["my-tho-day"],
    continueTrip: ["ho-chi-minh-city-mekong-delta"],
    familyByAge: {
      "0-2": "Skip long boats.",
      "3-5": "Mỹ Tho with sun hats.",
      "6-9": "Mỹ Tho.",
      "10-12": "Cần Thơ dawn market if you overnight.",
      teens: "Cần Thơ.",
    },
    jewishSummary: "None known.",
  },
  "phu-quoc": {
    bestFor: ["beach", "resort"],
    whoWillLove: "Families who can self-cater after Saigon Shabbat.",
    whoMightNot: "Anyone treating the island as a Friday city.",
    feelsLike: "A resort island with long hops.",
    dailyBudget: budget("Resort is the cost", "Cable car extra", "Bring baby food."),
    minNights: 3,
    maxNights: 5,
    neighborhoodIds: [],
    dayTripIds: ["pq-cable"],
    continueTrip: ["ho-chi-minh-city-phu-quoc"],
    familyByAge: {
      "0-2": "Resort paths, sun care.",
      "3-5": "Pool + beach.",
      "6-9": "Cable car if they like heights.",
      "10-12": "Cable car.",
      teens: "Pick one beach side and stay.",
    },
    jewishSummary: "None known. Self-cater or return to HCMC.",
  },
  "phong-nha": {
    bestFor: ["caves", "weekday wow"],
    whoWillLove: "Families who will overnight for Paradise Cave.",
    whoMightNot: "Anyone squeezing it into a Huế afternoon.",
    feelsLike: "A cave town, not a Jewish town.",
    dailyBudget: budget("Cave tickets add up", "Stay two nights", "Packed food."),
    minNights: 1,
    maxNights: 2,
    neighborhoodIds: [],
    dayTripIds: ["paradise-cave"],
    continueTrip: ["hue-phong-nha"],
    familyByAge: {
      "0-2": "Skip wet caves.",
      "3-5": "Maybe Phong Nha boat cave.",
      "6-9": "Boat cave + Paradise.",
      "10-12": "Paradise Cave.",
      teens: "Dark Cave mud if they want it.",
    },
    jewishSummary: "None known. Hội An or Huế-then-Hội An for Friday.",
  },
};

export function withTravel(dest: Destination): Destination {
  const extra = travelProfiles[dest.slug];
  return extra ? { ...dest, ...extra } : dest;
}
