import type { Venue } from "@/lib/schema";

export const venues: Venue[] = [
  {
    id: "kosher-saigon-chabad",
    destinationSlug: "ho-chi-minh-city",
    name: "Kosher restaurant at Chabad HCMC",
    kashrutClass: "community-operated",
    type: "restaurant",
    meatDairy: "unknown",
    address: "Chabad Center, 5A Nguyễn Đình Chiểu, District 1",
    hours: "Published Sun–Thu 9:00–21:00",
    fridayHours: "Published Friday 9:00–14:00",
    shabbatStatus: "Published Saturday closed. Shabbat meals by reservation, not walk-in restaurant hours.",
    whatsapp: "+84903102770",
    website: "https://koshersaigon.com/blogs/news/kosher-restaurant",
    mapsQuery: "Chabad of Vietnam 5A Nguyen Dinh Chieu",
    notes:
      "Operated with Chabad. This is not an independent hashgacha listing. Vegetarian street food elsewhere is not kosher.",
    verification: {
      status: "sourced",
      lastChecked: "2026-09-07",
      source: "koshersaigon.com restaurant page",
    },
  },
  {
    id: "chabad-hanoi-meals",
    destinationSlug: "hanoi",
    name: "Kosher meals — Chabad of Hanoi",
    kashrutClass: "community-operated",
    type: "meals",
    meatDairy: "unknown",
    address: "Confirm current Chabad of Hanoi address before ordering",
    shabbatStatus: "Shabbat meals by advance arrangement.",
    phone: "84-83-872-8225",
    website: "https://www.jewishhanoi.com/",
    mapsQuery: "Chabad of Hanoi To Ngoc Van",
    notes: "Site describes hotel delivery and catering. Order early. No other certified restaurant is listed here.",
    verification: {
      status: "sourced",
      lastChecked: "2026-09-07",
      source: "jewishhanoi.com kosher food pages",
    },
  },
  {
    id: "chabad-hoian-restaurant",
    destinationSlug: "hoi-an",
    name: "Kosher restaurant — Chabad Hoi An",
    kashrutClass: "community-operated",
    type: "restaurant",
    meatDairy: "unknown",
    address: "570A Cửa Đại, Cẩm Châu, Hội An",
    hours: "Published Sun–Thu 12:00–21:00",
    fridayHours: "Published Friday 11:30–14:30",
    shabbatStatus: "Shabbat meals by advance notice. Restaurant hours do not mean Shabbat walk-in service.",
    phone: "+84901356770",
    mapsQuery: "570A Cua Dai Hoi An",
    notes: "Contact before Friday. Old Town vegetarian restaurants are not kosher.",
    verification: {
      status: "sourced",
      lastChecked: "2026-09-07",
      source: "jewishvietnam.com Chabad Hoi An page",
    },
  },
  {
    id: "chabad-sapa-meals",
    destinationSlug: "sapa",
    name: "Chabad of Sapa meals",
    kashrutClass: "community-operated",
    type: "meals",
    meatDairy: "unknown",
    address: "12A Thác Bạc, Sa Pa (published on third-party listings)",
    shabbatStatus: "Unverified. Ask whether meals are being served the week you visit.",
    mapsQuery: "12A Thac Bac Sapa",
    notes: "Do not arrive hungry on Friday without a written confirmation.",
    verification: {
      status: "unverified",
      lastChecked: "2026-09-07",
      source: "Third-party Jewish travel listings",
    },
  },
];
