import type { Attraction } from "@/lib/schema";
import { attraction, livePrice } from "@/content/attractions/_factory";

export const daNangAttractions: Attraction[] = [
  attraction({
    id: "golden-bridge",
    destinationSlug: "da-nang",
    name: "Golden Bridge, Bà Nà Hills",
    category: "adventure",
    description: "Cable-car hill park and the gold bridge. A full paid theme-park day, 45 minutes from central Da Nang.",
    whyGo: "Plan 6–8 hours including the cable car. Kids usually enjoy Fantasy Park. Crowds 10:00–15:00. Do not add Marble Mountains.",
    duration: "6–8 hours",
    durationMin: 360,
    durationMax: 480,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 15.9952, lng: 107.9965 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets, cable cars, and a long day. Not for Shabbat.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    grabMin: 45,
    exclusiveWith: ["marble-da-nang", "son-tra"],
    flags: ["must-do", "kids", "full-day", "book-ahead", "teens", "rainy-day"],
    verification: livePrice,
  }),
  attraction({
    id: "my-khe",
    destinationSlug: "da-nang",
    name: "Mỹ Khê Beach",
    category: "beach",
    description: "City beach, wide sand, hotel strip. Cross the road with extreme care.",
    whyGo: "The reason to sleep in Da Nang midweek. Bring your own food. Not a Shabbat base.",
    duration: "2–4 hours",
    durationMin: 120,
    durationMax: 240,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.059, lng: 108.248 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No published synagogue walking radius. Weekday beach.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "must-do", "half-day", "free"],
  }),
  attraction({
    id: "son-tra",
    destinationSlug: "da-nang",
    name: "Sơn Trà Peninsula viewpoints",
    category: "viewpoint",
    description: "Winding road, monkeys, views. Lady Buddha statue is a religious site — you can stay at viewpoints.",
    whyGo: "2–3 hours by car. Motion sickness common. Not with Bà Nà the same day.",
    duration: "2.5–4 hours",
    durationMin: 150,
    durationMax: 240,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.106, lng: 108.277 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "A car day.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["golden-bridge"],
    flags: ["half-day", "teens"],
  }),
  attraction({
    id: "marble-da-nang",
    destinationSlug: "da-nang",
    name: "Marble Mountains",
    category: "cave",
    description: "Caves and pagodas. Elevator available. Hot. Pagodas are religious sites.",
    whyGo: "Half day from Da Nang or Hội An. Do not stack with Bà Nà.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "mixed",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.0036, lng: 108.2634 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and caves.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["golden-bridge"],
    flags: ["half-day", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "dragon-bridge",
    destinationSlug: "da-nang",
    name: "Dragon Bridge fire show",
    category: "evening",
    description: "Weekend evenings the dragon breathes fire and water. Crowds on the riverbank. Check the current night.",
    whyGo: "One evening if you sleep in Da Nang. Not worth a late Friday.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.061, lng: 108.227 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Usually Saturday or Sunday night — confirm. Not a Friday plan.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["evening", "kids", "free"],
  }),
  attraction({
    id: "han-market",
    destinationSlug: "da-nang",
    name: "Hàn Market",
    category: "market",
    description: "Indoor market, tourist stalls upstairs. Heat and bargaining.",
    whyGo: "Skip if short. Not kosher food.",
    duration: "30–45 minutes",
    durationMin: 30,
    durationMax: 45,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.068, lng: 108.223 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Shopping.",
    ages: ["10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["skip-if-short", "rainy-day"],
  }),
  attraction({
    id: "danang-museum-cham",
    destinationSlug: "da-nang",
    name: "Museum of Cham Sculpture",
    category: "museum",
    description: "Best indoor Cham collection. Air-con. Religious artifacts — museum context.",
    whyGo: "Rain plan. 60–90 minutes. Teens/adults.",
    duration: "60–90 minutes",
    durationMin: 60,
    durationMax: 90,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.0602, lng: 108.2235 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["rainy-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "asia-park",
    destinationSlug: "da-nang",
    name: "Sun Wheel / Asia Park",
    category: "kids",
    description: "Ferris wheel and amusement park on the river. Paid. Hot queues.",
    whyGo: "If kids need rides and you are not doing Bà Nà. Evening is cooler.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "mixed",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.04, lng: 108.227 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and rides.",
    ages: ["3-5", "6-9", "10-12", "teens"],
    stroller: "mixed",
    flags: ["kids", "evening", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "hoian-from-danang",
    destinationSlug: "da-nang",
    name: "Hội An evening from Da Nang",
    category: "day-trip",
    description: "45–60 minutes. Go for lanterns, back the same night. Not a Shabbat plan — sleep in Hội An Friday.",
    whyGo: "If you insist on a Da Nang hotel midweek. For Shabbat, just move.",
    duration: "4–6 hours",
    durationMin: 240,
    durationMax: 360,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 15.88, lng: 108.338 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Transfer and night market. Spend Friday in Hội An instead.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    grabMin: 50,
    flags: ["evening", "day-trip"],
  }),
  attraction({
    id: "namo-beach",
    destinationSlug: "da-nang",
    name: "Nam Ô / quieter north beach",
    category: "beach",
    description: "Less hotel-dense than Mỹ Khê. Still a road crossing.",
    whyGo: "If Mỹ Khê feels like a strip. Same sun rules.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.12, lng: 108.13 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Weekday beach.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "hidden-gem", "half-day", "free"],
  }),
  attraction({
    id: "danang-cathedral",
    destinationSlug: "da-nang",
    name: "Da Nang Cathedral (Pink Church) exterior",
    category: "architecture",
    description: "Pink church, photo stop. Religious building.",
    whyGo: "10 minutes if you pass it. Not a plan.",
    duration: "15 minutes",
    durationMin: 15,
    durationMax: 25,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.0678, lng: 108.2208 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "Religious site.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["quick-stop", "skip-if-short"],
  }),
  attraction({
    id: "helio-center",
    destinationSlug: "da-nang",
    name: "Helio Night Market / indoor games",
    category: "indoor",
    description: "Night market plus indoor play nearby depending on what’s open. Confirm on the day.",
    whyGo: "Heat/rain evening with kids if Bà Nà is already done.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.038, lng: 108.229 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Shopping and games.",
    ages: ["3-5", "6-9", "10-12", "teens"],
    stroller: "yes",
    flags: ["kids", "evening", "rainy-day"],
  }),
];
