import type { Attraction } from "@/lib/schema";
import { attraction, livePrice } from "@/content/attractions/_factory";

export const haLongAttractions: Attraction[] = [
  attraction({
    id: "halong-cruise",
    destinationSlug: "ha-long-bay",
    name: "Weekday day boat",
    category: "boat",
    description: "Karst seascape. Day boats avoid cabin keys and hotel electronics. No kosher kitchen.",
    whyGo: "The version that does not wreck Friday. 4–6 hours on the water plus the 3–4 hour transfer from Hanoi.",
    duration: "1 long day from Hanoi",
    durationMin: 600,
    durationMax: 840,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 20.9101, lng: 107.1839 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Never a Friday boarding for Shomer Shabbat travelers.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "full-day", "book-ahead", "day-trip"],
    verification: livePrice,
  }),
  attraction({
    id: "overnight-cruise",
    destinationSlug: "ha-long-bay",
    name: "Overnight cruise",
    category: "boat",
    description: "Cabins, keys, speakers, no kosher kitchen, tender boats. Beautiful and a poor Shomer Shabbat fit.",
    whyGo: "Only Sunday–Wednesday. Be back in Hanoi Thursday. Toddlers find it tiring.",
    duration: "1 or 2 nights",
    durationMin: 1440,
    durationMax: 2880,
    indoor: "mixed",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "required",
    coords: { lat: 20.92, lng: 107.18 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Electronics, tenders, no kitchen. Not a Shabbat base.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["full-day", "book-ahead", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "lan-ha",
    destinationSlug: "ha-long-bay",
    name: "Lan Ha Bay (via Cat Ba)",
    category: "boat",
    description: "Quieter karsts south of the classic route. Usually a Cat Ba overnight.",
    whyGo: "If Hạ Long harbor feels industrial. Same Friday rules.",
    duration: "1–2 days",
    durationMin: 480,
    durationMax: 1440,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 20.73, lng: 107.05 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats. Weekday.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["hidden-gem", "full-day", "book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "cat-ba",
    destinationSlug: "ha-long-bay",
    name: "Cat Ba town / national park",
    category: "nature",
    description: "Island town, trekking, kayaks. Ferry from Hải Phòng or a tour bundle.",
    whyGo: "A 2-night weekday add-on, not a Shabbat city.",
    duration: "2 days",
    durationMin: 960,
    durationMax: 1800,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 20.727, lng: 107.048 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No known Jewish infrastructure.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["day-trip", "teens", "full-day"],
  }),
  attraction({
    id: "sung-sot",
    destinationSlug: "ha-long-bay",
    name: "Sung Sot / Surprise Cave",
    category: "cave",
    description: "Standard day-boat cave. Stairs, crowds, gift shop. Often included.",
    whyGo: "You will probably stop here on a cheap day boat. Fine. Not a reason to pick the tour.",
    duration: "45 minutes",
    durationMin: 40,
    durationMax: 60,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.91, lng: 107.22 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Part of a boat ticket.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["skip-if-short"],
  }),
  attraction({
    id: "kayak-halong",
    destinationSlug: "ha-long-bay",
    name: "Kayak among karsts",
    category: "adventure",
    description: "Usually an add-on from a boat. Life jackets. Not with infants.",
    whyGo: "The part kids 7+ remember. Confirm they actually put you on the water, not just a photo cove.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 20.9, lng: 107.19 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["kids", "teens"],
  }),
  attraction({
    id: "halong-city",
    destinationSlug: "ha-long-bay",
    name: "Hạ Long city overnight",
    category: "neighborhood-walk",
    description: "The land city is a transit base, not the attraction. Sun Wheel and strip hotels.",
    whyGo: "Only to catch a morning boat. Sleep Hanoi if you can.",
    duration: "overnight",
    durationMin: 480,
    durationMax: 720,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: false,
    aircon: true,
    ticket: "free",
    booking: "none",
    coords: { lat: 20.95, lng: 107.08 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No synagogue map. Return to Hanoi for Friday.",
    ages: ["adults"],
    stroller: "yes",
    flags: ["skip-if-short"],
  }),
  attraction({
    id: "titanic-cave-skip",
    destinationSlug: "ha-long-bay",
    name: "Cable-car amusement add-ons on shore",
    category: "adventure",
    description: "Harbor-area amusement and cable products change names. They eat time you needed on the water.",
    whyGo: "Skip if you came for karsts. Kids who already did Bà Nà do not need another park.",
    duration: "skip",
    durationMin: 0,
    durationMax: 180,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.96, lng: 107.05 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["3-5", "6-9"],
    stroller: "mixed",
    flags: ["skip-if-short"],
  }),
];
