import type { Attraction } from "@/lib/schema";
import { attraction, checked, livePrice } from "@/content/attractions/_factory";

export const hanoiAttractions: Attraction[] = [
  attraction({
    id: "hoan-kiem",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-hoan-kiem",
    name: "Hoàn Kiếm Lake walk",
    localName: "Hồ Hoàn Kiếm",
    category: "neighborhood-walk",
    description:
      "A flat 1.5 km loop. The red Húc Bridge is the photo; you do not need to enter the island buildings.",
    whyGo: "Best no-ticket reset in the Old Quarter. Stroller-possible if you accept broken pavement.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0285, lng: 105.852 },
    address: "Hoàn Kiếm Lake, Hanoi",
    addressVi: "Hồ Hoàn Kiếm, Hà Nội",
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "Good walking activity if you stay nearby. No tickets on the loop.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    walkingFromJewishArea: "Old Quarter yes; Tây Hồ no — ride before Shabbat",
    grabMin: 25,
    flags: ["must-do", "kids", "free", "quick-stop", "shabbat-walk"],
    verification: checked,
  }),
  attraction({
    id: "old-quarter-walk",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-old-quarter",
    name: "Old Quarter street grid",
    localName: "Phố cổ",
    category: "neighborhood-walk",
    description:
      "36-street grid, honking, silk, tin, and fruit. Sidewalks disappear. Watch phones at the curb.",
    whyGo: "The actual Hanoi texture. Do it in daylight with children; nights are louder and tighter.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0338, lng: 105.8504 },
    religiousSite: false,
    shabbat: "streets-ok-skip-tickets",
    shabbatNote: "Walkable if you already sleep here. No shopping or paid sites.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    walkingFromJewishArea: "Not a Tây Hồ walk.",
    flags: ["must-do", "free", "teens"],
  }),
  attraction({
    id: "water-puppet",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-hoan-kiem",
    name: "Thăng Long water puppet show",
    category: "kids",
    description: "Indoor theatre by the lake. Shows last about an hour. Book the earlier slot with children.",
    whyGo: "Air-con, seats, and a defined end time — rare in Hanoi with young kids.",
    duration: "1 hour plus queue",
    durationMin: 70,
    durationMax: 100,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    priceAdult: "About 100,000₫",
    booking: "recommended",
    coords: { lat: 21.0316, lng: 105.853 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and a show. Weekday.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["kids", "rainy-day", "quick-stop", "book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "ethnology-museum",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-cau-giay",
    name: "Vietnam Museum of Ethnology",
    localName: "Bảo tàng Dân tộc học",
    category: "museum",
    description: "Indoor galleries plus an outdoor village of houses. Indoor half is the rain plan.",
    whyGo: "Best museum if you have children who need something to climb-look at, not war photos.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    priceAdult: "About 40,000₫",
    booking: "none",
    coords: { lat: 21.0406, lng: 105.7989 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and a ride from both Old Quarter and Tây Hồ.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    grabMin: 25,
    flags: ["must-do", "kids", "rainy-day", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "hoa-lo",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-hoan-kiem",
    name: "Hỏa Lò Prison museum",
    category: "museum",
    description: "Colonial prison, later ‘Hanoi Hilton.’ Graphic. Skip with young children.",
    whyGo: "Only if teens/adults want the history. Not a family default.",
    duration: "60–90 minutes",
    durationMin: 60,
    durationMax: 90,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 21.0254, lng: 105.8465 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["teens", "adults"],
    stroller: "mixed",
    flags: ["rainy-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "lotte-sky",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-ba-dinh",
    name: "Lotte Center observation deck",
    category: "viewpoint",
    description: "Mall + high observation deck. Air-con between. Tickets for the deck.",
    whyGo: "Rain or heat escape with a view. Mall bathrooms and a stroller path.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 21.0318, lng: 105.8124 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets, elevators, mall. Weekday.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    grabMin: 15,
    flags: ["kids", "rainy-day", "quick-stop"],
    verification: livePrice,
  }),
  attraction({
    id: "west-lake-loop",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-tay-ho",
    name: "West Lake path (Tây Hồ)",
    localName: "Hồ Tây",
    category: "neighborhood-walk",
    description: "Long lakeside path. Partial shade. Traffic still exists at crossings.",
    whyGo: "If you sleep in Tây Hồ this is your Shabbat walk — not the Old Quarter.",
    duration: "45–120 minutes",
    durationMin: 45,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.055, lng: 105.826 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "Best Shabbat outing if Chabad’s current pin is in Tây Hồ.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    walkingFromJewishArea: "Yes if you confirmed the Chabad pin.",
    flags: ["kids", "free", "shabbat-walk", "must-do"],
  }),
  attraction({
    id: "train-street",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-old-quarter",
    name: "Train street — from a safe distance",
    category: "viewpoint",
    description:
      "Cafés sit on active tracks. Do not sit kids on the rail. Watch one pass from a legal spot or skip.",
    whyGo: "Only a photo stop. Not a morning plan. Police sometimes clear cafés.",
    duration: "20–40 minutes",
    durationMin: 20,
    durationMax: 40,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0315, lng: 105.845 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Crowds, cafés, and a moving train. Skip.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["skip-if-short", "quick-stop", "teens"],
  }),
  attraction({
    id: "long-bien",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-old-quarter",
    name: "Long Biên Bridge walk",
    category: "viewpoint",
    description: "Colonial cantilever bridge. Motorbikes share the path. Hold children’s hands.",
    whyGo: "River air and a view of the tracks. Not with a stroller.",
    duration: "45–75 minutes",
    durationMin: 45,
    durationMax: 75,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0444, lng: 105.862 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "If you already walk from the Old Quarter. No tickets. Traffic is the risk.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["free", "teens", "shabbat-walk"],
  }),
  attraction({
    id: "mausoleum",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-ba-dinh",
    name: "Ba Đình Square / mausoleum exterior",
    category: "historic",
    description:
      "Huge square and the Ho Chi Minh Mausoleum. Interior has dress rules and queues. Exterior is free.",
    whyGo: "See the square. Skip the interior with small children unless they tolerate a silent line.",
    duration: "30–90 minutes",
    durationMin: 30,
    durationMax: 90,
    indoor: "mixed",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0368, lng: 105.8347 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Queues, guards, and a long walk. Weekday exterior only if you are already there.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["skip-if-short", "free"],
  }),
  attraction({
    id: "fine-arts",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-ba-dinh",
    name: "Vietnam Fine Arts Museum",
    category: "museum",
    description: "Colonial building, air-con rooms, lacquer and painting. Quiet.",
    whyGo: "Rain + adults/teens. Younger kids last 30 minutes.",
    duration: "60–90 minutes",
    durationMin: 60,
    durationMax: 90,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 21.0304, lng: 105.837 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["rainy-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "thang-long",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-ba-dinh",
    name: "Thăng Long Imperial Citadel",
    category: "historic",
    description: "Archaeological citadel next to Ba Đình. Hot courtyards, some indoor exhibits.",
    whyGo: "Ba Đình ruins and a defined indoor stretch. Skip if short.",
    duration: "1.5–2 hours",
    durationMin: 90,
    durationMax: 120,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 21.0353, lng: 105.84 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["half-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "weekend-night-market",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-old-quarter",
    name: "Old Quarter weekend night market",
    category: "market",
    description: "Friday–Sunday evenings, Hang Dao spine. Crowds, knock-offs, food smoke.",
    whyGo: "Atmosphere only. Not a shopping plan for kosher travelers. Hold kids tight.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.034, lng: 105.853 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Friday night market is after candles. Do not treat as a Shabbat outing.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["evening", "free", "teens"],
  }),
  attraction({
    id: "lenin-park",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-ba-dinh",
    name: "Thống Nhất Park",
    category: "kids",
    description: "Large city park, lake, playground pockets. Morning locals exercise.",
    whyGo: "Let kids run. Combine with a nearby museum. Bring water.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0167, lng: 105.844 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "If you already stay walking distance. No tickets.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["kids", "free", "shabbat-walk"],
  }),
  attraction({
    id: "vincom-ba-trieu",
    destinationSlug: "hanoi",
    neighborhoodId: "hanoi-hai-ba-trung",
    name: "Vincom Bà Triệu indoor mall",
    category: "indoor",
    description: "Mall, playground paid zones, air-con, bathrooms. Not an attraction — a weather tool.",
    whyGo: "When it is 38°C or pouring and the children are done.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "free",
    booking: "none",
    coords: { lat: 21.0116, lng: 105.8494 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Mall electronics and shopping.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["kids", "rainy-day"],
  }),
  attraction({
    id: "ninh-binh-day-from-hanoi",
    destinationSlug: "hanoi",
    name: "Ninh Bình day trip (leave Hanoi)",
    category: "day-trip",
    description: "2 hours each way. Boats at Tam Cốc or Tràng An. Packed kosher lunch. Back before dark.",
    whyGo: "The classic nature day from a Hanoi Shabbat base. Do not do this on Friday.",
    duration: "10–12 hours door to door",
    durationMin: 600,
    durationMax: 720,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 20.2506, lng: 105.9744 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "All-day travel and tickets. Midweek only.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["halong-day-from-hanoi"],
    flags: ["must-do", "day-trip", "full-day", "kids", "book-ahead"],
  }),
  attraction({
    id: "halong-day-from-hanoi",
    destinationSlug: "hanoi",
    name: "Hạ Long day boat (leave Hanoi)",
    category: "day-trip",
    description: "3–4 hours each way plus a boat. Brutal with toddlers. Overnight cruises wreck Friday.",
    whyGo: "Only if you will not also do Ninh Bình the same week at family pace. Thursday is the last sensible day.",
    duration: "12–14 hours",
    durationMin: 720,
    durationMax: 840,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 20.9101, lng: 107.1839 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Never a Friday boarding.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["ninh-binh-day-from-hanoi"],
    flags: ["day-trip", "full-day", "book-ahead", "skip-if-short"],
  }),
  attraction({
    id: "mai-chau-overnight",
    destinationSlug: "hanoi",
    name: "Mai Châu overnight (not a Friday)",
    category: "day-trip",
    description: "Valley homestays ~3.5 hours west. Pretty, rural, no kosher kitchen. Monday–Wednesday only.",
    whyGo: "Optional if you already did Ninh Bình. Skip with toddlers who still need a predictable bed.",
    duration: "2 days",
    durationMin: 1440,
    durationMax: 2160,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 20.655, lng: 105.086 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No Jewish infrastructure. Be in Hanoi Thursday night.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["day-trip", "hidden-gem", "skip-if-short"],
  }),
];
