import type { Attraction } from "@/lib/schema";
import { attraction, livePrice } from "@/content/attractions/_factory";

export const hcmcAttractions: Attraction[] = [
  attraction({
    id: "saigon-walking",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "District 1 parks and river edge",
    category: "neighborhood-walk",
    description: "Opera house lawn, walking street, and river breeze. Churches and temples are visible; you choose whether to enter.",
    whyGo: "The Shabbat-shaped outing if your hotel is in D1. Skip paid interiors.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.7765, lng: 106.7009 },
    addressVi: "Quận 1, TP. Hồ Chí Minh",
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "Best Shabbat outing if you skip paid sites and Grab.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    walkingFromJewishArea: "Often walkable from a District 1 hotel. Đa Kao Chabad is a measured walk — test Friday.",
    flags: ["must-do", "kids", "free", "shabbat-walk"],
  }),
  attraction({
    id: "war-remnants",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d3",
    name: "War Remnants Museum",
    category: "museum",
    description: "Graphic war history. Decide by age. The yard has aircraft; the upstairs photos are heavy.",
    whyGo: "Adults and older teens. Not a 6-year-old plan.",
    duration: "1.5–2 hours",
    durationMin: 90,
    durationMax: 130,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    priceAdult: "About 40,000₫",
    booking: "none",
    coords: { lat: 10.7798, lng: 106.692 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and usually a ride from Đa Kao.",
    ages: ["teens", "adults"],
    stroller: "yes",
    grabMin: 12,
    walkingFromJewishArea: "District 3 — usually a ride, not a Shabbat walk from Đa Kao",
    flags: ["must-do", "rainy-day", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "notre-dame-exterior",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Notre-Dame Cathedral exterior",
    category: "architecture",
    description: "Red-brick cathedral and the post office next door. Interior access changes with renovation — treat as exterior.",
    whyGo: "A 20-minute D1 photo stop. Combined with the walking street, not a half day.",
    duration: "20–40 minutes",
    durationMin: 20,
    durationMax: 40,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.7798, lng: 106.699 },
    religiousSite: true,
    shabbat: "streets-ok-skip-tickets",
    shabbatNote: "Exterior only. Do not enter.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["quick-stop", "free"],
  }),
  attraction({
    id: "central-post-office",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Saigon Central Post Office",
    category: "architecture",
    description: "Huge hall, maps, working counters. Free to walk through. Air-con blast at the door.",
    whyGo: "Five minutes of shade next to Notre-Dame. Kids like the ceiling.",
    duration: "15–30 minutes",
    durationMin: 15,
    durationMax: 30,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.7799, lng: 106.6998 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "A public building with electronics. Skip on Shabbat; use the park.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["quick-stop", "rainy-day", "free", "kids"],
  }),
  attraction({
    id: "ben-thanh",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Bến Thành Market",
    category: "market",
    description: "Tourist market. Aggressive selling. Heat. Not a kosher food plan.",
    whyGo: "See it once for 20 minutes or skip. Night market outside is slightly easier.",
    duration: "30–60 minutes",
    durationMin: 30,
    durationMax: 60,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.772, lng: 106.698 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Shopping.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["skip-if-short"],
  }),
  attraction({
    id: "walking-street",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Nguyễn Huệ walking street",
    category: "evening",
    description: "Pedestrian boulevard, fountains, evening crowds. Bikes still appear at the edges.",
    whyGo: "Evening with kids if you already sleep in D1. Bring water.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.7743, lng: 106.703 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "If you stay in walking range. No tickets.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["evening", "kids", "free", "shabbat-walk"],
  }),
  attraction({
    id: "independence-palace",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Independence Palace",
    category: "historic",
    description: "1960s presidential palace, bunkers, kitsch rooms. Tickets. Hot gardens.",
    whyGo: "Teens like the helicopters and radio room. Combine with Notre-Dame, not War Remnants the same morning if kids are young.",
    duration: "1.5–2 hours",
    durationMin: 90,
    durationMax: 120,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 10.777, lng: 106.6956 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["must-do", "teens", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "bitexco",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Bitexco SkyDeck",
    category: "viewpoint",
    description: "Paid observation deck. Mall/air-con below. Skip if haze is thick.",
    whyGo: "Heat escape with a view. Not must-do if you already did a deck elsewhere.",
    duration: "45–75 minutes",
    durationMin: 45,
    durationMax: 75,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 10.7719, lng: 106.7042 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and elevators.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["rainy-day", "kids", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "saigon-zoo",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Saigon Zoo and Botanical Gardens",
    category: "kids",
    description: "Old zoo plus gardens. Mixed animal welfare. Shade and room to run.",
    whyGo: "Young kids on a hot day. Pair with a nap, not a museum after.",
    duration: "2 hours",
    durationMin: 90,
    durationMax: 150,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 10.7876, lng: 106.705 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["0-2", "3-5", "6-9", "10-12"],
    stroller: "yes",
    flags: ["kids", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "d7-crescent",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d7",
    name: "Phú Mỹ Hưng crescent / Crescent Mall",
    category: "kids",
    description: "Planned district, wide sidewalks, mall, playgrounds. A Grab, not a D1 walk.",
    whyGo: "If you need stroller-friendly pavement and air-con. Sleep here only if you do not need a Shabbat walk to Chabad.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.728, lng: 106.721 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Too far from Đa Kao Chabad for a walk.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    grabMin: 25,
    flags: ["kids", "rainy-day"],
  }),
  attraction({
    id: "book-street",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Nguyễn Văn Bình Book Street",
    category: "neighborhood-walk",
    description: "Pedestrian book lane near Notre-Dame. Shade sails. Cafés.",
    whyGo: "A calmer D1 pocket for 20 minutes.",
    duration: "20–40 minutes",
    durationMin: 20,
    durationMax: 40,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.7808, lng: 106.6985 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "If already in D1. No tickets.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["quick-stop", "free", "shabbat-walk", "kids"],
  }),
  attraction({
    id: "rooftop-skip",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Hotel rooftop views — skip as a plan",
    category: "viewpoint",
    description: "Many rooftops are bars. Minimums, smoke, not kid rooms.",
    whyGo: "Do not build an afternoon around this. Use Bitexco or a park.",
    duration: "skip",
    durationMin: 0,
    durationMax: 30,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 10.776, lng: 106.701 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No.",
    ages: ["adults"],
    stroller: "no",
    flags: ["skip-if-short"],
  }),
  attraction({
    id: "cu-chi",
    destinationSlug: "ho-chi-minh-city",
    name: "Củ Chi tunnels",
    category: "day-trip",
    description: "90 minutes each way plus crawling in tunnels. Hot, dusty, firing range optional (skip).",
    whyGo: "Teens/adults only. Skip with under-10s. Not the same week as a Mekong day at family pace.",
    duration: "6–8 hours",
    durationMin: 360,
    durationMax: 480,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 11.1406, lng: 106.466 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "All-day travel.",
    ages: ["teens", "adults"],
    stroller: "no",
    exclusiveWith: ["mekong-day-from-saigon"],
    flags: ["day-trip", "full-day", "skip-if-short", "teens"],
  }),
  attraction({
    id: "mekong-day-from-saigon",
    destinationSlug: "ho-chi-minh-city",
    name: "Mekong day trip (Mỹ Tho area)",
    category: "day-trip",
    description: "2–3 hours each way, boats, coconut candy demos, packed lunch. Tourist loop is repetitive — still the easier family river day vs Cần Thơ overnight.",
    whyGo: "One Mekong weekday after Shabbat. Never Friday.",
    duration: "10–12 hours",
    durationMin: 600,
    durationMax: 720,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 10.360, lng: 106.36 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Traffic back to SGN can stall. Midweek.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["cu-chi"],
    flags: ["must-do", "day-trip", "full-day", "kids", "book-ahead"],
  }),
  attraction({
    id: "history-museum-hcmc",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "HCMC History Museum (in the zoo grounds)",
    category: "museum",
    description: "Air-con rooms next to the zoo. Fine if you already paid zoo/garden access depending on gate.",
    whyGo: "Add-on, not a standalone must-do.",
    duration: "45–75 minutes",
    durationMin: 45,
    durationMax: 75,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 10.7879, lng: 106.7048 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["rainy-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "binh-tay",
    destinationSlug: "ho-chi-minh-city",
    name: "Bình Tây wholesale market (Chợ Lớn)",
    category: "market",
    description: "Chinese-district wholesale. Real commerce, not souvenirs. Hot and chaotic.",
    whyGo: "Adults who like markets. Skip with strollers.",
    duration: "1 hour",
    durationMin: 45,
    durationMax: 90,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.749, lng: 106.651 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Far from Chabad. Shopping.",
    ages: ["teens", "adults"],
    stroller: "no",
    grabMin: 20,
    flags: ["hidden-gem", "skip-if-short"],
  }),
  attraction({
    id: "saigon-river-ferry",
    destinationSlug: "ho-chi-minh-city",
    neighborhoodId: "hcmc-d1",
    name: "Saigon waterbus / short ferry",
    category: "boat",
    description: "Cheap public boats on the river. Not a dinner cruise. Check last departure.",
    whyGo: "A 30-minute breeze. Kids like boats. Weekday only.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 10.776, lng: 106.708 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and a boat.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "quick-stop"],
    verification: livePrice,
  }),
];
