import type { Attraction } from "@/lib/schema";
import { attraction, livePrice } from "@/content/attractions/_factory";

export const hoiAnAttractions: Attraction[] = [
  attraction({
    id: "hoian-old-town",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Hội An Ancient Town streets",
    category: "historic",
    description: "Lantern streets, river, tailor shops. Ticketed historic houses sit among free streets.",
    whyGo: "Do the free streets in daylight with kids. Skip ticketed interiors on a short stay.",
    duration: "2–4 hours",
    durationMin: 120,
    durationMax: 240,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    priceNote: "Street walking is free. A ticket pack is only for historic houses.",
    booking: "none",
    coords: { lat: 15.877, lng: 108.328 },
    addressVi: "Phố cổ Hội An",
    religiousSite: false,
    shabbat: "streets-ok-skip-tickets",
    shabbatNote: "Streets are walkable. Skip ticketed houses and boat rides on Shabbat.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    walkingFromJewishArea: "About 15 minutes from published Chabad if that pin is current — test Friday.",
    flags: ["must-do", "kids", "free", "shabbat-walk"],
  }),
  attraction({
    id: "hoian-ticket-houses",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Ticketed historic houses",
    category: "historic",
    description: "Assembly halls, old merchant houses. Combined ticket. Queues at peak.",
    whyGo: "One or two houses if you like interiors. Not required for the town to work.",
    duration: "1.5–2 hours",
    durationMin: 90,
    durationMax: 120,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 15.8777, lng: 108.3275 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["half-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "an-bang",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-an-bang",
    name: "An Bàng Beach",
    category: "beach",
    description: "Beach 15–20 minutes from Old Town. Lounge chairs for hire. Sun is serious.",
    whyGo: "Kids’ reset after lantern streets. Bring your own food. Not a Shabbat walk from Cửa Đại Chabad unless you measured it.",
    duration: "2–4 hours",
    durationMin: 120,
    durationMax: 240,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 15.899, lng: 108.37 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Usually a Grab. Stay on the beach only if you already sleep there with food.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    grabMin: 15,
    flags: ["kids", "half-day", "must-do"],
  }),
  attraction({
    id: "cua-dai-beach",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-cua-dai",
    name: "Cửa Đại Beach",
    category: "beach",
    description: "Closer to the published Chabad address than An Bàng. Erosion has changed the sand year to year.",
    whyGo: "If you stay on Cửa Đại Road and need a short beach. Check the current shoreline.",
    duration: "1–3 hours",
    durationMin: 60,
    durationMax: 180,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 15.888, lng: 108.368 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "Only if your hotel walk is already confirmed. No tickets.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "free", "shabbat-walk"],
  }),
  attraction({
    id: "japanese-bridge",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Japanese Covered Bridge",
    category: "architecture",
    description: "Iconic bridge. Small shrine inside. Often ticketed to cross the interior.",
    whyGo: "Photograph from the street. Entering is optional.",
    duration: "15–30 minutes",
    durationMin: 15,
    durationMax: 30,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 15.877, lng: 108.3258 },
    religiousSite: true,
    shabbat: "streets-ok-skip-tickets",
    shabbatNote: "Look from the street. Do not buy a ticket.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["quick-stop", "must-do"],
    verification: livePrice,
  }),
  attraction({
    id: "night-lanterns",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Lantern evening (not Friday)",
    category: "evening",
    description: "Full-town lanterns, boats, crowds. Beautiful and exhausting with toddlers.",
    whyGo: "One weeknight. Saturday night after Shabbat if you have energy. Not candle-lighting time.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 15.8765, lng: 108.3285 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Friday night is Shabbat. Go another evening.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["evening", "must-do", "teens"],
  }),
  attraction({
    id: "basket-boat",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-cam-thanh",
    name: "Cẩm Thanh coconut basket boat",
    category: "boat",
    description: "Round boats in the water palm forest. Fun if priced in writing. Spinning ‘show’ is a common upsell.",
    whyGo: "Kids 5+ often love it. Agree the price before you sit down. 45–60 minutes is enough.",
    duration: "45–75 minutes plus transfer",
    durationMin: 90,
    durationMax: 150,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 15.876, lng: 108.351 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats and payment.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["kids", "half-day", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "tailor",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Tailor fitting — finish before Friday 2pm",
    category: "workshop",
    description: "Made-to-measure clothes. Needs two fittings. Do not pick up after candle lighting.",
    whyGo: "If you want clothes, start Sunday–Tuesday. Thursday last fitting. Friday is too late.",
    duration: "2–3 visits",
    durationMin: 120,
    durationMax: 240,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 15.878, lng: 108.329 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Shopping and fittings.",
    ages: ["teens", "adults"],
    stroller: "yes",
    flags: ["book-ahead", "rainy-day"],
  }),
  attraction({
    id: "marble-mountains",
    destinationSlug: "hoi-an",
    name: "Marble Mountains (from Hội An)",
    category: "day-trip",
    description: "Limestone caves and viewpoints on a hill toward Da Nang. Elevator optional. Skip shrine interiors.",
    whyGo: "Half day of caves and lookouts. Not stacked with Bà Nà.",
    duration: "3–4 hours",
    durationMin: 180,
    durationMax: 240,
    indoor: "mixed",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.003, lng: 108.263 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets, elevator, caves.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    grabMin: 25,
    exclusiveWith: ["ba-na-from-hoian"],
    flags: ["half-day", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "ba-na-from-hoian",
    destinationSlug: "hoi-an",
    name: "Bà Nà Hills full day (from Hội An)",
    category: "day-trip",
    description: "45–70 minutes to the cable car, then a full paid park day. Crowds 10:00–15:00.",
    whyGo: "Kids usually like the cable car and Fantasy Park. Treat as the whole day. Do not add Marble Mountains.",
    duration: "8–10 hours including transfer",
    durationMin: 480,
    durationMax: 600,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 15.995, lng: 107.996 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets, cable cars, and a long day.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    exclusiveWith: ["marble-mountains"],
    flags: ["must-do", "kids", "full-day", "day-trip", "book-ahead", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "rice-bike",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-cam-chau",
    name: "Countryside bicycle loop",
    category: "hike",
    description: "Flat rice paths. Traffic still appears. Sunrise is cooler.",
    whyGo: "Adults and older kids who already bike. Not a toddler plan.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 15.89, lng: 108.34 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Bikes.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["half-day", "teens"],
  }),
  attraction({
    id: "hoian-museum",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Hội An Museum of Folk Culture",
    category: "museum",
    description: "Small indoor museum on the ticket circuit. Air-con is limited.",
    whyGo: "Rain + one indoor stop. Skip if you already hate museums.",
    duration: "30–45 minutes",
    durationMin: 30,
    durationMax: 45,
    indoor: "indoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "none",
    coords: { lat: 15.8774, lng: 108.3288 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["rainy-day", "quick-stop", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "thu-bon-boat",
    destinationSlug: "hoi-an",
    neighborhoodId: "hoian-old-town",
    name: "Thu Bồn river boat",
    category: "boat",
    description: "Short tourist boats from the old town quay. Evening is prettier and more crowded.",
    whyGo: "Optional. Basket boats are more ‘activity’ for kids.",
    duration: "30–45 minutes",
    durationMin: 30,
    durationMax: 45,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 15.8762, lng: 108.326 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["evening", "kids"],
    verification: livePrice,
  }),
  attraction({
    id: "hue-day-from-hoian",
    destinationSlug: "hoi-an",
    name: "Huế day trip",
    category: "day-trip",
    description: "2.5–3.5 hours each way. Citadel is huge and hot. Packed lunch. Leave early.",
    whyGo: "Only if you will not spend a night in Huế. Better as an overnight weekday if you care about tombs.",
    duration: "12 hours",
    durationMin: 660,
    durationMax: 780,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 16.4637, lng: 107.5909 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "All-day travel. Not Friday.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["day-trip", "full-day", "skip-if-short"],
  }),
];
