import type { Attraction } from "@/lib/schema";
import { attraction, livePrice } from "@/content/attractions/_factory";

export const ninhBinhAttractions: Attraction[] = [
  attraction({
    id: "trang-an",
    destinationSlug: "ninh-binh",
    name: "Tràng An boat",
    category: "boat",
    description: "Rowed boats through limestone and paddies. Some routes pass pagodas — described so you can choose.",
    whyGo: "The calmer, more ‘park’ boat than Tam Cốc. 2–3 hours on the water. Packed lunch.",
    duration: "2–3 hours on the water",
    durationMin: 150,
    durationMax: 240,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 20.25, lng: 105.916 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Ticketed boats. Midweek only.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["tam-coc"],
    flags: ["must-do", "kids", "half-day", "book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "tam-coc",
    destinationSlug: "ninh-binh",
    name: "Tam Cốc boat",
    category: "boat",
    description: "Classic ‘dry Halong’ row. Shorter river, more vendors at the dock. Pagodas on some sightlines.",
    whyGo: "If Tràng An tickets are sold out. Not both in one day with children.",
    duration: "1.5–2.5 hours",
    durationMin: 90,
    durationMax: 150,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.211, lng: 105.928 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Ticketed boats.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    exclusiveWith: ["trang-an"],
    flags: ["must-do", "kids", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "hoa-lu",
    destinationSlug: "ninh-binh",
    name: "Hoa Lư old capital temples",
    category: "historic",
    description: "Two temples on the old capital site. Religious buildings. Often bundled with a boat.",
    whyGo: "Add-on, not the reason to come. You can skip and still have a full nature day.",
    duration: "45–75 minutes",
    durationMin: 45,
    durationMax: 75,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.285, lng: 105.905 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and temples.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "hang-mua",
    destinationSlug: "ninh-binh",
    name: "Hang Múa viewpoint",
    category: "hike",
    description: "500 stone steps, dragon statue, rice-paddy view. Brutal midday.",
    whyGo: "Teens/fit adults. Not with toddlers. Sunrise beats noon.",
    duration: "1.5–2 hours",
    durationMin: 90,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.226, lng: 105.916 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and stairs.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["teens", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "bai-dinh",
    destinationSlug: "ninh-binh",
    name: "Bái Đính Pagoda complex",
    category: "historic",
    description: "Huge modern Buddhist complex. Golf carts. Clearly religious.",
    whyGo: "Usually skip if you already have a boat. Heat plus a shrine campus.",
    duration: "1.5–2 hours",
    durationMin: 90,
    durationMax: 120,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.276, lng: 105.868 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "Religious site and tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "ninh-binh-bike",
    destinationSlug: "ninh-binh",
    name: "Tam Cốc bicycle among paddies",
    category: "hike",
    description: "Flat bikes, some traffic. Morning only.",
    whyGo: "If you overnight. Not a toddler bike.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 20.213, lng: 105.927 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Bikes.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["teens", "half-day"],
  }),
  attraction({
    id: "mua-cave-boat-combo",
    destinationSlug: "ninh-binh",
    name: "Do not combine Tràng An + Hang Múa + Hoa Lư in one family day",
    category: "day-trip",
    description: "Tour menus stack everything. With children you get heat stroke, not three highlights.",
    whyGo: "Pick one boat + maybe Hang Múa for teens. Return to Hanoi for dinner.",
    duration: "skip the stack",
    durationMin: 0,
    durationMax: 60,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.25, lng: 105.97 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "n/a",
    ages: ["adults"],
    stroller: "no",
    flags: ["skip-if-short"],
  }),
  attraction({
    id: "ninh-binh-station",
    destinationSlug: "ninh-binh",
    name: "Arrive by train from Hanoi",
    category: "day-trip",
    description: "About 2 hours. Station is not the boat dock — you still need a taxi/Grab.",
    whyGo: "Useful if you hate the highway. Still a weekday.",
    duration: "2 hours each way",
    durationMin: 120,
    durationMax: 150,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 20.244, lng: 105.974 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Trains.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "van-long",
    destinationSlug: "ninh-binh",
    name: "Vân Long nature reserve boat",
    category: "nature",
    description: "Quieter wetland boat. Fewer vendors. Birds, not karst density of Tràng An.",
    whyGo: "If you already did Tam Cốc on a previous trip. Hidden-gem pace.",
    duration: "2 hours",
    durationMin: 90,
    durationMax: 150,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 20.35, lng: 105.86 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["hidden-gem", "half-day", "kids"],
    verification: livePrice,
  }),
  attraction({
    id: "ninh-binh-night",
    destinationSlug: "ninh-binh",
    name: "Overnight vs day trip",
    category: "neighborhood-walk",
    description: "Tam Cốc town is small. One night only helps if you want sunrise Hang Múa.",
    whyGo: "Families based in Hanoi for Shabbat should day-trip. Overnight is for photographers.",
    duration: "decision",
    durationMin: 30,
    durationMax: 60,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 20.2506, lng: 105.9744 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No Jewish infrastructure. Sleep Hanoi Thursday/Friday.",
    ages: ["adults"],
    stroller: "yes",
    flags: ["skip-if-short"],
  }),
];
