import type { Attraction } from "@/lib/schema";
import { attraction, livePrice } from "@/content/attractions/_factory";

export const hueAttractions: Attraction[] = [
  attraction({
    id: "hue-citadel",
    destinationSlug: "hue",
    name: "Imperial Citadel",
    category: "historic",
    description: "Walled imperial city. Large, hot, ticketed. Bring water and a carrier.",
    whyGo: "The reason to stop in Huế. Budget 2–4 hours. Morning only with children.",
    duration: "2–4 hours",
    durationMin: 120,
    durationMax: 240,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.4696, lng: 107.5775 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets. Midweek. Shabbat in Hội An.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["must-do", "half-day", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "tu-duc-tomb",
    destinationSlug: "hue",
    name: "Tự Đức Tomb",
    category: "historic",
    description: "Lakes and pavilions. Prettier than some tombs. Still hot.",
    whyGo: "Pick ONE tomb, not a tomb circuit with kids.",
    duration: "1.5 hours",
    durationMin: 75,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.431, lng: 107.565 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "khai-dinh",
    destinationSlug: "hue",
    name: "Khải Định Tomb",
    category: "historic",
    description: "Hill tomb, mosaic interior, stairs. Most ‘wow’ per minute.",
    whyGo: "If you only do one tomb besides the citadel, this is the one.",
    duration: "60–90 minutes",
    durationMin: 60,
    durationMax: 90,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.398, lng: 107.59 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and a drive.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "perfume-river",
    destinationSlug: "hue",
    name: "Perfume River dragon boat",
    category: "boat",
    description: "Tourist boats, sometimes a pagoda stop (Thiên Mụ — religious). Agree the itinerary.",
    whyGo: "Optional. Citadel + one tomb is enough.",
    duration: "1–2 hours",
    durationMin: 60,
    durationMax: 120,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 16.463, lng: 107.585 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["kids", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "thien-mu",
    destinationSlug: "hue",
    name: "Thiên Mụ Pagoda",
    category: "historic",
    description: "Riverside pagoda, seven-story tower. Religious site. Often a boat stop.",
    whyGo: "A look from outside is enough for many families.",
    duration: "30–45 minutes",
    durationMin: 30,
    durationMax: 45,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.454, lng: 107.545 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "Religious site.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["quick-stop"],
  }),
  attraction({
    id: "hue-food-street-skip",
    destinationSlug: "hue",
    name: "Imperial food street — not kosher",
    category: "market",
    description: "Famous local food. Vegetarian still isn’t kosher.",
    whyGo: "Do not treat Huế cuisine as a kosher plan. Packed food from Hội An/Hanoi.",
    duration: "skip as food plan",
    durationMin: 0,
    durationMax: 30,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 16.47, lng: 107.59 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "n/a",
    ages: ["adults"],
    stroller: "mixed",
    flags: ["skip-if-short"],
  }),
  attraction({
    id: "phong-nha-from-hue",
    destinationSlug: "hue",
    name: "Continue to Phong Nha (overnight)",
    category: "day-trip",
    description: "3–4 hours north. Caves need a night. Not a Huế afternoon add-on.",
    whyGo: "If the trip has cave days. Be back toward Hội An by Thursday for Shabbat.",
    duration: "2 days",
    durationMin: 1440,
    durationMax: 2160,
    indoor: "mixed",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 17.59, lng: 106.283 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No Jewish infrastructure.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["day-trip", "full-day", "book-ahead"],
  }),
];

export const sapaAttractions: Attraction[] = [
  attraction({
    id: "sapa-cat-cat",
    destinationSlug: "sapa",
    name: "Cat Cat village path",
    category: "hike",
    description: "Downhill village walk. Steep, often wet. Ticket gate.",
    whyGo: "The easy ‘first hike.’ Carriers beat strollers. Confirm distance from the current Chabad pin.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 22.325, lng: 103.831 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Ticket gate. Not for Shabbat.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    walkingFromJewishArea: "Near town; confirm distance from Chabad",
    flags: ["must-do", "half-day", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "fansipan",
    destinationSlug: "sapa",
    name: "Fansipan cable car",
    category: "adventure",
    description: "Long cable, summit complex, weather can be zero visibility. Full half-day plus queues.",
    whyGo: "Kids like the cable. Summit temples are religious — you can stay on the viewing decks.",
    duration: "4–6 hours",
    durationMin: 240,
    durationMax: 360,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 22.336, lng: 103.775 },
    religiousSite: true,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and cable cars.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["must-do", "kids", "full-day", "book-ahead", "rainy-day"],
    verification: livePrice,
  }),
  attraction({
    id: "sapa-town",
    destinationSlug: "sapa",
    name: "Sapa town square walk",
    category: "neighborhood-walk",
    description: "Stone square, church exterior, fog. Steep streets.",
    whyGo: "If Chabad is confirmed open, this is the Shabbat-shaped walk — test the hill Friday.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 22.3364, lng: 103.8438 },
    religiousSite: false,
    shabbat: "walk-ok",
    shabbatNote: "Only after you confirm Chabad and the walk. No tickets.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["free", "shabbat-walk", "kids"],
  }),
  attraction({
    id: "ta-van",
    destinationSlug: "sapa",
    name: "Tả Van terrace trek",
    category: "hike",
    description: "Mud, buffalo, homestay villages. Guide useful. Slippery.",
    whyGo: "Fit adults/teens. Not with toddlers. Not Friday.",
    duration: "4–7 hours",
    durationMin: 240,
    durationMax: 420,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 22.305, lng: 103.89 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Trek.",
    ages: ["teens", "adults"],
    stroller: "no",
    flags: ["full-day", "teens"],
  }),
  attraction({
    id: "sapa-church",
    destinationSlug: "sapa",
    name: "Stone church exterior",
    category: "architecture",
    description: "Town-center church. Religious building.",
    whyGo: "Photo on the square walk. Do not need to enter.",
    duration: "10 minutes",
    durationMin: 10,
    durationMax: 20,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 22.337, lng: 103.844 },
    religiousSite: true,
    shabbat: "streets-ok-skip-tickets",
    shabbatNote: "Exterior on a town walk.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["quick-stop"],
  }),
];

export const mekongAttractions: Attraction[] = [
  attraction({
    id: "my-tho-day",
    destinationSlug: "mekong-delta",
    name: "Mỹ Tho / Bến Tre day loop",
    category: "boat",
    description: "Closest river day from Saigon. Coconut candy stops, small canals, packed lunch.",
    whyGo: "The family Mekong. One weekday. Back before dark.",
    duration: "10 hours from HCMC",
    durationMin: 540,
    durationMax: 720,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 10.36, lng: 106.36 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Friday traffic back to SGN can stall.",
    ages: ["3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "kids", "full-day", "day-trip", "book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "can-tho-overnight",
    destinationSlug: "mekong-delta",
    name: "Cần Thơ overnight + Cai Rang market",
    category: "boat",
    description: "4 hours from HCMC. Floating market at dawn. Tourist but still the ‘realer’ river city.",
    whyGo: "Only if you have two weekdays. Not a Shabbat city.",
    duration: "2 days",
    durationMin: 1440,
    durationMax: 2160,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 10.0452, lng: 105.7469 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Return to District 1 for Friday.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["full-day", "day-trip", "book-ahead"],
  }),
  attraction({
    id: "floating-market",
    destinationSlug: "mekong-delta",
    name: "Cái Răng floating market",
    category: "market",
    description: "Wholesale boats at sunrise. You will be on a tourist boat looking at other tourist boats. Still worth one dawn.",
    whyGo: "If you overnight Cần Thơ. Skip as a same-day from Saigon — too far.",
    duration: "2–3 hours at dawn",
    durationMin: 120,
    durationMax: 180,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 10.0, lng: 105.75 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "kids"],
    verification: livePrice,
  }),
];

export const phongNhaAttractions: Attraction[] = [
  attraction({
    id: "phong-nha-cave-boat",
    destinationSlug: "phong-nha",
    name: "Phong Nha Cave boat",
    category: "cave",
    description: "The accessible cave: boat in, walk, boat out. Wet floors. Life jackets.",
    whyGo: "The family cave. Do this before you look at Sơn Đoòng ads.",
    duration: "3–4 hours",
    durationMin: 180,
    durationMax: 240,
    indoor: "mixed",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 17.582, lng: 106.27 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and boats. Weekday. Shabbat in Hội An.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "kids", "half-day", "book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "paradise-cave",
    destinationSlug: "phong-nha",
    name: "Paradise Cave (Thiên Đường)",
    category: "cave",
    description: "Long wooden walkway in a huge dry cave. Stairs at the start. Cool air.",
    whyGo: "Best ‘wow’ cave that is still a day trip, not an expedition.",
    duration: "2–3 hours",
    durationMin: 120,
    durationMax: 180,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 17.52, lng: 106.22 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "teens", "half-day", "rainy-day"],
    verification: livePrice,
  }),
  attraction({
    id: "dark-cave",
    destinationSlug: "phong-nha",
    name: "Dark Cave zipline / mud",
    category: "adventure",
    description: "Zipline, swim, mud. Change of clothes. Not with small children.",
    whyGo: "Teens. Do not combine with Sơn Đoòng fantasies the same afternoon.",
    duration: "3–4 hours",
    durationMin: 180,
    durationMax: 240,
    indoor: "mixed",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 17.55, lng: 106.25 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Adventure tickets.",
    ages: ["teens", "adults"],
    stroller: "no",
    flags: ["teens", "half-day", "book-ahead"],
  }),
  attraction({
    id: "son-doong-skip",
    destinationSlug: "phong-nha",
    name: "Sơn Đoòng expedition — usually skip",
    category: "adventure",
    description: "Multi-day, lottery/permit, expensive, expert. Not a family add-on.",
    whyGo: "If you did not book a year ahead, you are not going. Do Paradise + Phong Nha Cave.",
    duration: "multi-day",
    durationMin: 0,
    durationMax: 60,
    indoor: "mixed",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 17.45, lng: 106.28 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Expedition.",
    ages: ["adults"],
    stroller: "no",
    flags: ["skip-if-short", "book-ahead"],
  }),
];

export const nhaTrangAttractions: Attraction[] = [
  attraction({
    id: "nt-beach",
    destinationSlug: "nha-trang",
    name: "Nha Trang municipal beach",
    category: "beach",
    description: "City beach, promenade, motorbikes. Hotel pools are often better with toddlers.",
    whyGo: "Weekday resort stop with packed food. Not a Friday landing.",
    duration: "half day",
    durationMin: 120,
    durationMax: 300,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 12.2388, lng: 109.1967 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No published Chabad.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "half-day", "free"],
  }),
  attraction({
    id: "vinwonders",
    destinationSlug: "nha-trang",
    name: "VinWonders island park",
    category: "kids",
    description: "Ferry plus a huge paid park. Full day. Crowds.",
    whyGo: "If the children need a park and you already skipped Bà Nà. Not both in one trip at slow pace.",
    duration: "7–9 hours",
    durationMin: 420,
    durationMax: 540,
    indoor: "mixed",
    rainOk: true,
    heatOk: false,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 12.21, lng: 109.22 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and a ferry.",
    ages: ["3-5", "6-9", "10-12", "teens"],
    stroller: "mixed",
    flags: ["kids", "full-day", "book-ahead"],
    verification: livePrice,
  }),
  attraction({
    id: "nt-islands",
    destinationSlug: "nha-trang",
    name: "Four-island boat",
    category: "boat",
    description: "Snorkel tourist loop. Sun, upsells, mediocre reefs. Motion.",
    whyGo: "Teens maybe. Toddlers no. Hotel pool often wins.",
    duration: "5–6 hours",
    durationMin: 300,
    durationMax: 360,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 12.2, lng: 109.23 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Boats.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["full-day", "skip-if-short", "teens"],
  }),
];

export const daLatAttractions: Attraction[] = [
  attraction({
    id: "xuan-huong",
    destinationSlug: "da-lat",
    name: "Xuân Hương Lake loop",
    category: "neighborhood-walk",
    description: "Cool air, swan boats, centrish walk. The easiest family hour in Da Lat.",
    whyGo: "Arrival afternoon. Not a ticket farm.",
    duration: "45–90 minutes",
    durationMin: 45,
    durationMax: 90,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 11.941, lng: 108.438 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "No Jewish walking map. Weekday town.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "yes",
    flags: ["kids", "must-do", "free", "quick-stop"],
  }),
  attraction({
    id: "valley-of-love",
    destinationSlug: "da-lat",
    name: "Valley of Love",
    category: "kids",
    description: "Paid park, boats, photo sets. Cheesy. Kids sometimes like it.",
    whyGo: "If you need a contained park. Skip if short.",
    duration: "2 hours",
    durationMin: 90,
    durationMax: 150,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 11.96, lng: 108.43 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["3-5", "6-9", "10-12"],
    stroller: "mixed",
    flags: ["kids", "half-day", "skip-if-short"],
    verification: livePrice,
  }),
  attraction({
    id: "datanla",
    destinationSlug: "da-lat",
    name: "Đatanla waterfall / alpine coaster",
    category: "adventure",
    description: "Waterfall plus optional sled ride. Height rules. Wet.",
    whyGo: "Teens. Combine with one other viewpoint, not five.",
    duration: "2 hours",
    durationMin: 90,
    durationMax: 150,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 11.9, lng: 108.45 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["teens", "half-day"],
    verification: livePrice,
  }),
  attraction({
    id: "crazy-house",
    destinationSlug: "da-lat",
    name: "Crazy House (Hằng Nga)",
    category: "architecture",
    description: "Gaudi-ish guesthouse museum. Stairs, low rails. Fun and slightly unsafe with toddlers.",
    whyGo: "Unique 45–75 minutes. Not a half day.",
    duration: "45–75 minutes",
    durationMin: 45,
    durationMax: 75,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "paid",
    booking: "none",
    coords: { lat: 11.935, lng: 108.431 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "teens", "kids", "rainy-day"],
    verification: livePrice,
  }),
];

export const phuQuocAttractions: Attraction[] = [
  attraction({
    id: "phu-quoc-beach",
    destinationSlug: "phu-quoc",
    name: "Resort beach day",
    category: "beach",
    description: "Sand and pool. Bring your own food. Island groceries are weak for kosher products.",
    whyGo: "After a Saigon Shabbat. Fly back Thursday if you need Friday in the city.",
    duration: "half day or more",
    durationMin: 180,
    durationMax: 480,
    indoor: "outdoor",
    rainOk: false,
    heatOk: false,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.22, lng: 103.96 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Only if you are already staying on the island with food prepared.",
    ages: ["0-2", "3-5", "6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "must-do", "half-day"],
  }),
  attraction({
    id: "pq-cable",
    destinationSlug: "phu-quoc",
    name: "Hon Thom cable car",
    category: "adventure",
    description: "Long sea cable to an island park. Full half-day. Tickets.",
    whyGo: "The ‘wow’ island outing. Crowds. Not Shabbat.",
    duration: "4–6 hours",
    durationMin: 240,
    durationMax: 360,
    indoor: "mixed",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: true,
    ticket: "paid",
    booking: "recommended",
    coords: { lat: 10.16, lng: 103.97 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Tickets and cable.",
    ages: ["6-9", "10-12", "teens", "adults"],
    stroller: "mixed",
    flags: ["kids", "full-day", "book-ahead", "teens"],
    verification: livePrice,
  }),
  attraction({
    id: "pq-north-south",
    destinationSlug: "phu-quoc",
    name: "North vs south beaches",
    category: "beach",
    description: "South/Ong Lang vs Long Beach hotel strip. Distances are long — pick a side and stay.",
    whyGo: "Do not hotel-hop the island. Grab coverage thins at night.",
    duration: "decision",
    durationMin: 30,
    durationMax: 60,
    indoor: "outdoor",
    rainOk: true,
    heatOk: true,
    shade: true,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 10.2899, lng: 103.984 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Resort distances are not a synagogue map.",
    ages: ["adults"],
    stroller: "yes",
    flags: ["skip-if-short"],
  }),
];

export const haGiangAttractions: Attraction[] = [
  attraction({
    id: "ha-giang-loop",
    destinationSlug: "ha-giang",
    name: "Hà Giang loop (driver, not motorbike with kids)",
    category: "hike",
    description: "3–4 midweek days of mountain roads. Spectacular. Motion sickness. No kosher kitchen.",
    whyGo: "Adults/teens who can finish Thursday and return to Hanoi or confirmed Sapa. Poor with toddlers.",
    duration: "3–4 days",
    durationMin: 2880,
    durationMax: 4320,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "paid",
    booking: "required",
    coords: { lat: 23.2, lng: 105.3 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Friday on the loop will not work if you need minyan or kosher meals.",
    ages: ["teens", "adults"],
    stroller: "no",
    flags: ["full-day", "teens", "book-ahead"],
  }),
  attraction({
    id: "ma-pi-leng",
    destinationSlug: "ha-giang",
    name: "Ma Pi Leng pass viewpoint",
    category: "viewpoint",
    description: "The postcard pass. Usually day 2–3 of the loop. Wind and drop-offs.",
    whyGo: "The photo. Hold children. Not a stroll.",
    duration: "30–60 minutes on site",
    durationMin: 30,
    durationMax: 60,
    indoor: "outdoor",
    rainOk: false,
    heatOk: true,
    shade: false,
    aircon: false,
    ticket: "free",
    booking: "none",
    coords: { lat: 23.23, lng: 105.4 },
    religiousSite: false,
    shabbat: "not-shabbat",
    shabbatNote: "Remote roads.",
    ages: ["10-12", "teens", "adults"],
    stroller: "no",
    flags: ["must-do", "teens"],
  }),
];
